globalThis.DigiBoardSentence=(()=>{
 'use strict';
 const persons=[{word:'ik',label:'ik',n:0,h:'heb',z:'ben'},{word:'jij',label:'jij',n:1,h:'hebt',z:'bent'},{word:'zij',label:'hij / zij',n:2,h:'heeft',z:'is'},{word:'wij',label:'wij',n:3,h:'hebben',z:'zijn'},{word:'jullie',label:'jullie',n:3,h:'hebben',z:'zijn'},{word:'zij',label:'zij (meer mensen)',n:3,h:'hebben',z:'zijn'}];
 const tenses=[{id:'present',label:'Tegenwoordige tijd',short:'Nu',color:'#26744a',hint:'persoon + werkwoord + rest'},{id:'past',label:'Verleden tijd',short:'Toen',color:'#245eab',hint:'persoon + werkwoord in de verleden tijd + rest'},{id:'perfect',label:'Voltooide tijd',short:'Gedaan',color:'#b13d47',hint:'persoon + hebben of zijn + rest + voltooid deelwoord'}];
 // Forms and complements are authored together, including auxiliary and separated particle.
 const verbs=[
 ['werken','werk','werkt','werkte','werkten','gewerkt','h','thuis'],['wonen','woon','woont','woonde','woonden','gewoond','h','in Utrecht'],['leren','leer','leert','leerde','leerden','geleerd','h','Nederlands'],['koken','kook','kookt','kookte','kookten','gekookt','h','rijst'],['drinken','drink','drinkt','dronk','dronken','gedronken','h','water'],['eten','eet','eet','at','aten','gegeten','h','een appel'],['lezen','lees','leest','las','lazen','gelezen','h','een boek'],['slapen','slaap','slaapt','sliep','sliepen','geslapen','h','acht uur'],['maken','maak','maakt','maakte','maakten','gemaakt','h','een foto'],['kopen','koop','koopt','kocht','kochten','gekocht','h','een brood'],['zoeken','zoek','zoekt','zocht','zochten','gezocht','h','een sleutel'],['luisteren','luister','luistert','luisterde','luisterden','geluisterd','h','naar muziek'],['bellen','bel','belt','belde','belden','gebeld','h','met een vriend'],['wachten','wacht','wacht','wachtte','wachtten','gewacht','h','op de bus'],['spelen','speel','speelt','speelde','speelden','gespeeld','h','een spel'],['praten','praat','praat','praatte','praatten','gepraat','h','met de buren'],['lopen','loop','loopt','liep','liepen','gelopen','z','naar de winkel'],['fietsen','fiets','fietst','fietste','fietsten','gefietst','z','naar school'],['gaan','ga','gaat','ging','gingen','gegaan','z','naar huis'],['komen','kom','komt','kwam','kwamen','gekomen','z','naar de les'],['zien','zie','ziet','zag','zagen','gezien','h','een vogel'],['geven','geef','geeft','gaf','gaven','gegeven','h','een cadeau'],['opstaan','sta','staat','stond','stonden','opgestaan','z','om zeven uur','op'],['meenemen','neem','neemt','nam','namen','meegenomen','h','een tas','mee']
 ].map(([id,ik,hij,past,pastPlural,pp,aux,rest,particle=''])=>({id,ik,hij,past,pastPlural,pp,aux,rest,particle}));
 const random=n=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n;};
 const key=q=>q.person+'|'+q.verb+'|'+q.tense;
 const validCard=q=>q&&Number.isInteger(q.person)&&q.person>=0&&q.person<6&&verbs.some(v=>v.id===q.verb)&&tenses.some(t=>t.id===q.tense);
 function example(q){const p=persons[q.person],v=verbs.find(v=>v.id===q.verb);if(!validCard(q))return'';const subject=p.word[0].toUpperCase()+p.word.slice(1);if(q.tense==='perfect')return`${subject} ${p[v.aux]} ${v.rest} ${v.pp}.`;const verb=q.tense==='past'?(p.n===3?v.pastPlural:v.past):(p.n===3?(v.particle?v.id.slice(0):v.id):p.n===0?v.ik:v.hij);return`${subject} ${verb} ${v.rest}${v.particle&&p.n!==3?' '+v.particle:v.particle&&q.tense==='past'?' '+v.particle:''}.`;}
 // Plural separable verbs split in a main clause too (wij staan ... op).
 function answer(q){const p=persons[q.person],v=verbs.find(v=>v.id===q.verb);if(!validCard(q))return'';if(v.particle&&p.n===3&&q.tense==='present')return`${p.word[0].toUpperCase()+p.word.slice(1)} ${v.id.slice(v.particle.length)} ${v.rest} ${v.particle}.`;return example(q);}
 function preset(level){return{persons:level==='A0'?[0,1,2]:[0,1,2,3,4,5],verbs:verbs.slice(0,level==='A0'?6:level==='A1'?12:24).map(v=>v.id),tenses:level==='B1'?['present','past','perfect']:level==='A2'?['present','perfect']:['present']};}
 function valid(s){return !s||s.version===1&&s.options&&Array.isArray(s.options.persons)&&s.options.persons.length>0&&s.options.persons.every(n=>Number.isInteger(n)&&n>=0&&n<6)&&Array.isArray(s.options.verbs)&&s.options.verbs.length>0&&s.options.verbs.every(id=>verbs.some(v=>v.id===id))&&Array.isArray(s.options.tenses)&&s.options.tenses.length>0&&s.options.tenses.every(id=>tenses.some(t=>t.id===id))&&(!s.current||validCard(s.current))&&Array.isArray(s.history)&&s.history.length<=20&&s.history.every(validCard)&&Array.isArray(s.used)&&s.used.length<=432;}
 function state(d){if(!valid(d.sentenceGame)||!d.sentenceGame)d.sentenceGame={version:1,options:preset(d.settings.learningLevel),current:null,history:[],used:[],cycle:0};return d.sentenceGame;}
 function draw(s){const all=s.options.persons.flatMap(person=>s.options.verbs.flatMap(verb=>s.options.tenses.map(tense=>({person,verb,tense}))));let pool=all.filter(q=>!s.used.includes(key(q)));if(!pool.length){s.used=[];s.cycle++;pool=all;}if(pool.length>1&&s.current)pool=pool.filter(q=>key(q)!==key(s.current));const q=pool[random(pool.length)];if(s.current)s.history.push(s.current);s.history=s.history.slice(-20);s.current=q;s.used.push(key(q));return q;}
 function migrate(d){
  if(!d.settings.sentenceOnBoard){if(!d.settings.diceStyle||['numbers','sentence'].includes(d.settings.diceStyle))d.settings.diceStyle='sentence';d.settings.sentenceOnBoard=true;}
 }
 function validBoard(b){return !b||b.version===1&&Number.isInteger(b.lastTurn)&&b.players&&typeof b.players==='object'&&!Array.isArray(b.players)&&Object.values(b.players).every(validCard)&&Array.isArray(b.used)&&b.used.length<=432&&b.used.every(k=>typeof k==='string');}
 function board(d){if(!validBoard(d.session.sentenceBoard))delete d.session.sentenceBoard;return d.session.sentenceBoard??={version:1,lastTurn:0,players:{},used:[]};}
 function boardDraw(d,person){
  const b=board(d),o=state(d).options,p=d.session.players[d.session.active],previous=b.players[p.id];
  const all=o.verbs.flatMap(verb=>o.tenses.map(tense=>({person,verb,tense})));let pool=all.filter(q=>!b.used.includes(key(q)));
  if(!pool.length){b.used=b.used.filter(k=>!k.startsWith(person+'|'));pool=all;}
  if(pool.length>1&&previous)pool=pool.filter(q=>key(q)!==key(previous));
  const q=pool[random(pool.length)];b.players[p.id]=q;b.used.push(key(q));return q;
 }
 function ensure(d){if(d.settings.diceStyle!=='sentence')return;const s=d.session,b=board(d);if(s.turn>0&&Number.isInteger(s.result)&&s.result>=1&&s.result<=6&&s.turn!==b.lastTurn){boardDraw(d,s.result-1);b.lastTurn=s.turn;}}
 function another(d){const b=board(d),p=d.session.players[d.session.active],q=b.players[p.id];return q?boardDraw(d,q.person):null;}
 function task(base,settings,session,playerId=session.players[session.active]?.id){
  const normal=DigiBoardMatrix.task(base,settings,{...session,active:Math.max(0,session.players.findIndex(p=>p.id===playerId))}),q=session.sentenceBoard?.players?.[playerId];
  if(!q)return{...normal,lessonId:'sentence-start',title:'Gooi en maak een zin',instruction:'Gooi met de dobbelsteen. De pion loopt en de worp bepaalt de persoon.',input:'1 ik · 2 jij · 3 hij/zij · 4 wij · 5 jullie · 6 zij (meer mensen)',model:'',support:'Gooi eerst met de dobbelsteen.',retry:'Gooi om een persoon en een werkwoord te krijgen.',family:'Zinnen maken',grammar:'persoon + werkwoord + tijd'};
  const v=verbs.find(v=>v.id===q.verb),t=tenses.find(t=>t.id===q.tense),label=persons[q.person].label,model=answer(q),instruction='Maak één zin met '+label+' en '+v.id+'.',input=t.label+' · '+t.short+'. Je kunt gebruiken: '+v.rest+'.';
  return{...normal,lessonId:'sentence-'+key(q),title:label+' · '+v.id,instruction,input,model,support:t.hint+' · Begin met '+label+' …',retry:'Maak nog een zin met dezelfde persoon, hetzelfde werkwoord en dezelfde tijd.',family:'Zinnen maken',grammar:t.label,help:'Voorbeeld: '+model,partner:'Luister naar de zin. Maak daarna zelf een zin.',teacher:'De worp bepaalt de persoon én het aantal stappen. Het vaknummer bepaalt de persoon niet. Kies alleen tijden en werkwoorden die al geoefend zijn.',criterion:'De zin gebruikt de opgegeven persoon en de juiste werkwoordsvorm in de gekozen tijd.',teacherCriterion:'De zin gebruikt de opgegeven persoon en tijd.',printSummary:instruction+' '+input,printShort:instruction,variants:{instap:{instruction,support:t.hint},basis:{instruction},extra:{instruction:'Maak nog een zin met andere informatie.'}},sentence:q};
 }
 function connect(h){
  const {$,root,read,save,render,dialog,esc}=h;
  const settings=document.createElement('section');settings.className='db-sentence-settings';settings.innerHTML='<h4>Zinnen maken op de kaart</h4><p>De worp verplaatst de pion én kiest de persoon.</p><p>1 ik · 2 jij · 3 hij/zij · 4 wij · 5 jullie · 6 zij (meer mensen)</p><button type="button" id="db-sentence-settings-open">Werkwoorden en tijden kiezen</button>';$('pp-panel-dice').append(settings);
  const choice=document.createElement('section');choice.className='db-sentence-settings';choice.innerHTML='<h4>Oefening op de kaart</h4><label for="db-board-exercise">Wat oefen je na de worp?</label><select id="db-board-exercise"><option value="sentence">Zinnen maken · worp bepaalt de persoon</option><option value="numbers">Taalopdrachten · vorm bepaalt de opdracht</option></select><button type="button" id="db-sentence-board-config">Werkwoorden en tijden kiezen</button>';$('pp-panel-board').querySelector('.db-board-select').after(choice);
  $('db-board-exercise').onchange=()=>{if(h.busy())return;read().settings.diceStyle=$('db-board-exercise').value;save();render();};
  const style=document.createElement('style');style.textContent='.db-sentence-settings{margin-top:20px}.db-sentence-choices{display:flex;flex-wrap:wrap;gap:10px 20px;margin-bottom:20px}.db-sentence-choices label{display:flex;align-items:center;gap:8px;min-width:145px}.db-sentence-choices input{width:20px!important;height:20px}#pp-task[data-sentence-active="true"] #pp-task-title{color:var(--sentence-color,#173c4b)}#pp-task[data-sentence-active="true"] #pp-partner{border-left:5px solid var(--sentence-color,#173c4b);padding-left:12px}';root.append(style);
  function configure(){
   const d=read(),s=state(d),o=s.options;
   dialog('Zinnen maken op de kaart','<p>Gooi op het bord. Het aantal ogen bepaalt de persoon: 1 ik, 2 jij, 3 hij/zij, 4 wij, 5 jullie, 6 zij (meer mensen).</p><p>Groen: nu. Blauw: verleden tijd. Rood: voltooide tijd.</p><button type="button" id="db-sentence-preset">Gebruik startkeuze voor '+esc(DigiBoardMatrix.route(d.settings).label)+'</button>'+[['tenses','Tijden',tenses],['verbs','Werkwoorden',verbs.map(v=>({id:v.id,label:v.id}))]].map(([k,label,rows])=>'<h3>'+label+'</h3><div class="db-sentence-choices">'+rows.map(v=>'<label><input type="checkbox" data-sentence-option="'+k+'" value="'+v.id+'" '+(o[k].includes(v.id)?'checked':'')+'>'+esc(v.label)+'</label>').join('')+'</div>').join('')+'<p id="db-sentence-error" role="alert"></p><button type="button" id="db-sentence-apply" class="pp-primary">Gebruik deze keuze</button>',()=>{
    $('db-sentence-preset').onclick=()=>{s.options={...preset(d.settings.learningLevel),persons:[0,1,2,3,4,5]};save();configure();};
    $('db-sentence-apply').onclick=()=>{const next={persons:[0,1,2,3,4,5]};for(const k of ['tenses','verbs'])next[k]=[...root.querySelectorAll('[data-sentence-option="'+k+'"]:checked')].map(i=>i.value);if(!next.verbs.length||!next.tenses.length){$('db-sentence-error').textContent='Kies minstens één werkwoord en één tijd.';return;}s.options=next;save();h.closeDialog();render();};
   });
  }
  $('db-sentence-settings-open').onclick=configure;$('db-sentence-board-config').onclick=configure;
  function sync(page){
   const d=read(),on=d.settings.diceStyle==='sentence',s=d.session,p=s.players[s.active],q=s.sentenceBoard?.players?.[p.id];
   $('db-board-exercise').value=on?'sentence':'numbers';$('pp-pace').disabled=on;$('db-sentence-board-config').hidden=!on;settings.hidden=!on;
   $('pp-task').dataset.sentenceActive=String(on);if(!on){for(const id of ['db-matrix-hint','db-matrix-next'])if($(id))$(id).hidden=false;return;}
   const t=q?tenses.find(t=>t.id===q.tense):null;$('pp-task').style.setProperty('--sentence-color',t?.color||'#173c4b');
   $('db-game-level').textContent='ZINNEN OP DE KAART · '+DigiBoardMatrix.route(d.settings).label;
   if(!h.busy())$('pp-result').textContent=q?'Worp '+(q.person+1)+' · '+persons[q.person].label+' · '+(q.person+1)+' stappen':'Gooi: ogen = stappen én persoon';
   const ready=!!q&&!!s.selected;
   for(const id of ['pp-help','pp-extra','db-matrix-hint','db-matrix-next','db-lesson-support'])if($(id))$(id).hidden=!ready;
   if(ready&&!h.busy()){$('pp-role-a').textContent='Jouw zin';$('pp-role-b').textContent='Tijd en woorden';$('pp-task-label').textContent=DigiBoardMatrix.route(d.settings).label+' · WORP '+(q.person+1)+' = '+persons[q.person].label+' · VAK '+s.selected;}
   if(!q&&!h.busy()){$('pp-task-title').textContent='Gooi en maak een zin';$('pp-instruction').textContent='Klik op de dobbelsteen. De pion loopt het aantal ogen. Dezelfde worp bepaalt de persoon.';$('pp-role-a').textContent='Zo speel je';$('pp-role-b').textContent='De worp bepaalt';$('pp-partner').textContent='1 ik · 2 jij · 3 hij/zij · 4 wij · 5 jullie · 6 zij (meer mensen)';$('pp-practice-hint').textContent='';}
   if(q&&!s.selected&&p.pos===s.board.tasks.length+1&&!h.busy()){$('pp-task-title').textContent=persons[q.person].label+' · '+q.verb;$('pp-instruction').textContent='Je bent bij het einde. Maak nog één zin met '+persons[q.person].label+' en '+q.verb+'.';$('pp-partner').textContent=t.label+' · Je kunt gebruiken: '+verbs.find(v=>v.id===q.verb).rest+'.';}
  }
  return{sync};
 }
 return{persons,verbs,tenses,preset,valid,state,draw,answer,migrate,validBoard,ensure,another,task,connect};
})();
