globalThis.DigiBoardSentence=(()=>{
 'use strict';
 const persons=[{word:'ik',label:'ik',n:0,h:'heb',z:'ben'},{word:'jij',label:'jij',n:1,h:'hebt',z:'bent'},{word:'zij',label:'hij / zij',n:2,h:'heeft',z:'is'},{word:'wij',label:'wij',n:3,h:'hebben',z:'zijn'},{word:'jullie',label:'jullie',n:3,h:'hebben',z:'zijn'},{word:'zij',label:'zij (meer mensen)',n:3,h:'hebben',z:'zijn'}];
 const tenses=[{id:'present',label:'Tegenwoordige tijd',short:'Nu',color:'#26744a',hint:'persoon + werkwoord + rest'},{id:'past',label:'Verleden tijd',short:'Toen',color:'#245eab',hint:'persoon + werkwoord in de verleden tijd + rest'},{id:'perfect',label:'Voltooide tijd',short:'Gedaan',color:'#b13d47',hint:'persoon + hebben of zijn + rest + voltooid deelwoord'}];
 // Forms and complements are authored together, including auxiliary and separated particle.
 const verbs=[
 ['werken','werk','werkt','werkte','werkten','gewerkt','h','thuis'],['wonen','woon','woont','woonde','woonden','gewoond','h','in Utrecht'],['leren','leer','leert','leerde','leerden','geleerd','h','Nederlands'],['koken','kook','kookt','kookte','kookten','gekookt','h','rijst'],['drinken','drink','drinkt','dronk','dronken','gedronken','h','water'],['eten','eet','eet','at','aten','gegeten','h','een appel'],['lezen','lees','leest','las','lazen','gelezen','h','een boek'],['slapen','slaap','slaapt','sliep','sliepen','geslapen','h','acht uur'],['maken','maak','maakt','maakte','maakten','gemaakt','h','een foto'],['kopen','koop','koopt','kocht','kochten','gekocht','h','een brood'],['zoeken','zoek','zoekt','zocht','zochten','gezocht','h','een sleutel'],['luisteren','luister','luistert','luisterde','luisterden','geluisterd','h','naar muziek'],['bellen','bel','belt','belde','belden','gebeld','h','met een vriend'],['wachten','wacht','wacht','wachtte','wachtten','gewacht','h','op de bus'],['spelen','speel','speelt','speelde','speelden','gespeeld','h','een spel'],['praten','praat','praat','praatte','praatten','gepraat','h','met de buren'],['lopen','loop','loopt','liep','liepen','gelopen','z','naar de winkel'],['fietsen','fiets','fietst','fietste','fietsten','gefietst','z','naar school'],['gaan','ga','gaat','ging','gingen','gegaan','z','naar huis'],['komen','kom','komt','kwam','kwamen','gekomen','z','naar de les'],['zien','zie','ziet','zag','zagen','gezien','h','een vogel'],['geven','geef','geeft','gaf','gaven','gegeven','h','een cadeau'],['opstaan','sta','staat','stond','stonden','opgestaan','z','om zeven uur','op'],['meenemen','neem','neemt','nam','namen','meegenomen','h','een tas','mee']
 ].map(([id,ik,hij,past,pastPlural,pp,aux,rest,particle=''])=>({id,ik,hij,past,pastPlural,pp,aux,rest,particle}));
 const random=n=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n;};
 const key=q=>q.person+'|'+q.verb+'|'+q.tense;
 const validCard=q=>q&&Number.isInteger(q.person)&&q.person>=0&&q.person<6&&verbs.some(v=>v.id===q.verb)&&tenses.some(t=>t.id===q.tense);
 function example(q){const p=persons[q.person],v=verbs.find(v=>v.id===q.verb);if(!validCard(q))return'';const subject=p.word[0].toUpperCase()+p.word.slice(1);if(q.tense==='perfect')return`${subject} ${p[v.aux]} ${v.rest} ${v.pp}.`;const verb=q.tense==='past'?(p.n===3?v.pastPlural:v.past):(p.n===3?(v.particle?v.id.slice(0):v.id):p.n===0?v.ik:v.hij);return`${subject} ${verb} ${v.rest}${v.particle&&p.n!==3?' '+v.particle:v.particle&&q.tense==='past'?' '+v.particle:''}.`;}
 // Plural separable verbs split in a main clause too (wij staan ... op).
 function answer(q){const p=persons[q.person],v=verbs.find(v=>v.id===q.verb);if(!validCard(q))return'';if(v.particle&&p.n===3&&q.tense==='present')return`${p.word[0].toUpperCase()+p.word.slice(1)} ${v.id.slice(v.particle.length)} ${v.rest} ${v.particle}.`;return example(q);}
 function preset(level){return{persons:level==='A0'?[0,1,2]:[0,1,2,3,4,5],verbs:verbs.slice(0,level==='A0'?6:level==='A1'?12:24).map(v=>v.id),tenses:level==='B1'?['present','past','perfect']:level==='A2'?['present','perfect']:['present']};}
 function valid(s){return !s||s.version===1&&s.options&&Array.isArray(s.options.persons)&&s.options.persons.length>0&&s.options.persons.every(n=>Number.isInteger(n)&&n>=0&&n<6)&&Array.isArray(s.options.verbs)&&s.options.verbs.length>0&&s.options.verbs.every(id=>verbs.some(v=>v.id===id))&&Array.isArray(s.options.tenses)&&s.options.tenses.length>0&&s.options.tenses.every(id=>tenses.some(t=>t.id===id))&&(!s.current||validCard(s.current))&&Array.isArray(s.history)&&s.history.length<=20&&s.history.every(validCard)&&Array.isArray(s.used)&&s.used.length<=432;}
 function state(d){if(!valid(d.sentenceGame)||!d.sentenceGame)d.sentenceGame={version:1,options:preset(d.settings.learningLevel),current:null,history:[],used:[],cycle:0};return d.sentenceGame;}
 function draw(s){const all=s.options.persons.flatMap(person=>s.options.verbs.flatMap(verb=>s.options.tenses.map(tense=>({person,verb,tense}))));let pool=all.filter(q=>!s.used.includes(key(q)));if(!pool.length){s.used=[];s.cycle++;pool=all;}if(pool.length>1&&s.current)pool=pool.filter(q=>key(q)!==key(s.current));const q=pool[random(pool.length)];if(s.current)s.history.push(s.current);s.history=s.history.slice(-20);s.current=q;s.used.push(key(q));return q;}
 function connect(h){const {$,root,read,save,render,dialog,esc}=h;let reveal='',stamp='';const view=document.createElement('section');view.id='pp-sentencegame';view.hidden=true;view.innerHTML='<div class="db-sentence-heading"><div><p class="pp-kicker" id="db-sentence-level"></p><h2>Eenvoudig zinnenspel</h2></div><button type="button" id="db-sentence-config" class="pp-secondary">Kies de oefening</button></div><p class="db-sentence-instruction">Maak één zin met deze persoon en dit werkwoord.</p><div class="db-sentence-cards" aria-live="polite"><div><small>Persoon · worp <span id="db-sentence-number">–</span></small><strong id="db-sentence-person">?</strong></div><div><small>Werkwoord</small><strong id="db-sentence-verb">?</strong><span id="db-sentence-rest"></span></div><div id="db-sentence-time"><small>Tijd</small><strong id="db-sentence-tense">?</strong><span id="db-sentence-tense-name"></span></div></div><p id="db-sentence-response" aria-live="polite"></p><div class="db-sentence-actions"><button type="button" id="db-sentence-roll" class="pp-primary">Gooi</button><button type="button" id="db-sentence-back" class="pp-secondary">Vorige</button><button type="button" id="db-sentence-hint" class="pp-secondary">Hulp</button><button type="button" id="db-sentence-example" class="pp-secondary">Voorbeeld</button></div><p class="db-sentence-legend">1 ik · 2 jij · 3 hij/zij · 4 wij · 5 jullie · 6 zij (meer mensen)</p><p class="pp-note" id="db-sentence-selection"></p>';
 $('pp-game').after(view);
 const config=document.createElement('section');config.className='db-sentence-settings';config.innerHTML='<h4>Eenvoudig zinnenspel</h4><p>Een persoon, een werkwoord en een tijd. Kies alleen wat de groep al heeft geoefend.</p><button type="button" id="db-sentence-settings-open">Personen, werkwoorden en tijden kiezen</button>';$('pp-panel-dice').append(config);
 const style=document.createElement('style');style.textContent='#praatpad-board #pp-sentencegame{flex:1;min-height:0;padding:clamp(18px,3vw,48px);background:#faf6ed;display:flex;flex-direction:column;justify-content:center;gap:20px}#praatpad-board #pp-sentencegame[hidden]{display:none!important}.db-sentence-heading{display:flex;justify-content:space-between;align-items:center;gap:20px}.db-sentence-heading h2{font-size:clamp(24px,3vw,42px)}.db-sentence-instruction{font-size:clamp(19px,2vw,30px)}.db-sentence-cards{display:grid;grid-template-columns:1fr 1.5fr 1fr;gap:20px}.db-sentence-cards>div{border:2px solid #c9c1b4;border-radius:18px;padding:clamp(16px,3vw,40px);display:flex;flex-direction:column;justify-content:center;gap:12px;background:#fff;min-height:180px}.db-sentence-cards strong{font-size:clamp(26px,4vw,60px);line-height:1.1}.db-sentence-cards small{font-size:16px}.db-sentence-cards span{font-size:clamp(16px,1.7vw,24px)}#db-sentence-time{color:white}.db-sentence-actions{display:flex;gap:12px;flex-wrap:wrap}.db-sentence-actions button{min-width:100px}#db-sentence-response{min-height:44px;font-size:clamp(20px,2.2vw,32px);font-weight:600}.db-sentence-legend{font-size:16px}.db-sentence-choices{display:flex;flex-wrap:wrap;gap:8px 20px;margin-bottom:18px}.db-sentence-choices label{display:flex;align-items:center;gap:8px;min-width:130px}.db-sentence-choices input{width:20px!important;height:20px}.db-sentence-settings{margin-top:24px}@media(max-height:760px) and (min-width:900px){#praatpad-board #pp-sentencegame{gap:12px;padding:20px}.db-sentence-cards>div{padding:22px;min-height:160px}}@media(max-width:650px){.db-sentence-cards{grid-template-columns:1fr;gap:12px}.db-sentence-cards>div{min-height:110px;padding:18px}.db-sentence-heading{align-items:flex-start;flex-direction:column}.db-sentence-cards strong{font-size:32px}}';root.append(style);
 function configure(){const s=state(read()),o=s.options;dialog('Kies de oefening','<p>Groen: nu. Blauw: toen. Rood: gedaan. De docent kiest welke vormen al bekend zijn.</p><button type="button" id="db-sentence-preset">Gebruik startkeuze voor '+esc(DigiBoardMatrix.route(read().settings).label)+'</button>'+[['persons','Personen',persons.map((p,i)=>({id:i,label:(i+1)+' · '+p.label}))],['tenses','Tijden',tenses],['verbs','Werkwoorden',verbs.map(v=>({id:v.id,label:v.id}))]].map(([k,label,rows])=>'<h3>'+label+'</h3><div class="db-sentence-choices">'+rows.map(v=>'<label><input type="checkbox" data-sentence-option="'+k+'" value="'+v.id+'" '+(o[k].includes(v.id)?'checked':'')+'>'+esc(v.label)+'</label>').join('')+'</div>').join('')+'<p id="db-sentence-error" role="alert"></p><button type="button" id="db-sentence-apply" class="pp-primary">Gebruik deze keuze</button>',()=>{$('db-sentence-preset').onclick=()=>{s.options=preset(read().settings.learningLevel);s.current=null;s.history=[];reveal='';save();configure();};$('db-sentence-apply').onclick=()=>{const next={};for(const k of ['persons','verbs','tenses'])next[k]=[...root.querySelectorAll('[data-sentence-option="'+k+'"]:checked')].map(i=>k==='persons'?+i.value:i.value);if(Object.values(next).some(a=>!a.length)){$('db-sentence-error').textContent='Kies minstens één persoon, één werkwoord en één tijd.';return;}s.options=next;s.history=[];if(s.current&&!next.persons.includes(s.current.person)||s.current&&!next.verbs.includes(s.current.verb)||s.current&&!next.tenses.includes(s.current.tense))s.current=null;reveal='';save();h.closeDialog();render();};});}
 $('db-sentence-config').onclick=configure;$('db-sentence-settings-open').onclick=configure;
 $('db-sentence-roll').onclick=()=>{const d=read(),s=state(d);draw(s);if(d.settings.workForm==='spotlight')DigiBoardLearning.speaker(d.session,d.roster,true);reveal='';save();render();};
 $('db-sentence-back').onclick=()=>{const s=state(read());if(!s.history.length)return;s.current=s.history.pop();reveal='';save();render();};
 $('db-sentence-hint').onclick=()=>{reveal=reveal==='hint'?'':'hint';sync('sentencegame');};$('db-sentence-example').onclick=()=>{reveal=reveal==='example'?'':'example';sync('sentencegame');};
 function sync(page){view.hidden=page!=='sentencegame';config.hidden=read().settings.diceStyle!=='sentence';if(view.hidden)return;const d=read(),s=state(d),q=s.current,ts=q?tenses.find(t=>t.id===q.tense):null,v=q?verbs.find(v=>v.id===q.verb):null,nextStamp=q?key(q):'';if(stamp!==nextStamp)reveal='';stamp=nextStamp;$('db-sentence-level').textContent=DigiBoardMatrix.route(d.settings).label;$('db-sentence-number').textContent=q?q.person+1:'–';$('db-sentence-person').textContent=q?persons[q.person].label:'?';$('db-sentence-verb').textContent=v?.id||'?';$('db-sentence-rest').textContent=v?'Je kunt gebruiken: '+v.rest:'';$('db-sentence-tense').textContent=ts?.short||'?';$('db-sentence-tense-name').textContent=ts?.label||'Gooi om te beginnen';$('db-sentence-time').style.background=ts?.color||'#516075';$('db-sentence-response').textContent=!q?'':reveal==='example'?'Bijvoorbeeld: '+answer(q):reveal==='hint'?ts.hint+' · Begin met '+(q.person===2?'Hij of zij':persons[q.person].word)+' …':'';$('db-sentence-back').disabled=!s.history.length;for(const id of ['db-sentence-hint','db-sentence-example'])$(id).disabled=!q;$('db-sentence-hint').setAttribute('aria-pressed',reveal==='hint');$('db-sentence-example').setAttribute('aria-pressed',reveal==='example');const count=s.options.persons.length*s.options.verbs.length*s.options.tenses.length,speaker=d.settings.workForm==='spotlight'?DigiBoardLearning.speaker(d.session,d.roster):'';$('db-sentence-selection').textContent=s.options.verbs.length+' '+(s.options.verbs.length===1?'werkwoord':'werkwoorden')+' · '+s.options.persons.length+' '+(s.options.persons.length===1?'persoon':'personen')+' · '+s.options.tenses.length+' '+(s.options.tenses.length===1?'tijd':'tijden')+' · '+count+' '+(count===1?'combinatie':'combinaties')+(speaker?' · Iedereen maakt de zin. Hardop: '+speaker:'');}
 return{sync};}
 return{persons,verbs,tenses,preset,valid,state,draw,answer,connect};
})();
