const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),server=require('../server.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});const results=[];
try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=`http://127.0.0.1:${server.address().port}/Start-Praatpad.html?kaart=bos-bosroute`;await page.goto(base);await page.waitForSelector('#tr-app-trigger');
for(const width of [320,390,768,1280,1920])for(const colorScheme of ['light','dark'])for(const text of [100,200]){
 await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});await page.evaluate(text=>document.documentElement.style.fontSize=text===200?'32px':'16px',text);await page.waitForTimeout(80);
 const before=await page.locator('#pp-map').boundingBox(),taskBefore=await page.locator('#pp-task').boundingBox();await page.locator('#tr-app-trigger').click();
 const m=await page.evaluate(()=>{const h=document.querySelector('.pp-brand'),p=document.querySelector('#tr-app-menu'),n=document.querySelector('.tr-product-name'),r=h.getBoundingClientRect();return {height:r.height,accent:parseFloat(getComputedStyle(h).borderBottomWidth),menuRight:p.getBoundingClientRect().right,nameVisible:n.scrollWidth<=n.clientWidth&&n.getBoundingClientRect().right<document.querySelector('#pp-main-tools').getBoundingClientRect().left,hit:[...p.querySelectorAll('a'),document.querySelector('#tr-app-trigger')].every(e=>e.getBoundingClientRect().height>=44),alignment:[...p.querySelectorAll('.tr-divider')].every(e=>Math.abs(e.getBoundingClientRect().left-document.querySelector('.pp-brand-divider').getBoundingClientRect().left)<1),ids:[...document.querySelectorAll('[id]')].map(e=>e.id)}});
 assert.equal(m.height,60);assert.equal(m.accent,2);assert(m.menuRight<=width);assert(m.nameVisible);assert(m.hit);assert(m.alignment);assert.deepEqual(await page.locator('[id$=DRIEHOEK_BOEK_ACCENT]').evaluateAll(es=>es.map(e=>getComputedStyle(e).fill)),['rgb(0, 144, 242)','rgb(89, 64, 45)','rgb(40, 95, 71)','rgb(199, 99, 73)']);assert.equal(await page.locator('.tr-missies').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(252, 248, 237)');assert.equal(new Set(m.ids).size,m.ids.length);assert.deepEqual(await page.locator('#pp-map').boundingBox(),before);assert.deepEqual(await page.locator('#pp-task').boundingBox(),taskBefore);
 await page.screenshot({path:`tests/artifacts/appmenu-${width}-${colorScheme}-${text}.png`});await page.keyboard.press('Escape');assert.equal(await page.locator('#tr-app-trigger').getAttribute('aria-expanded'),'false');assert(await page.locator('#tr-app-trigger').evaluate(e=>e===document.activeElement));
 results.push({width,colorScheme,text,header:m.height,accent:m.accent,lessonShift:0});
}
await page.evaluate(()=>document.documentElement.style.fontSize='16px');await page.setViewportSize({width:1280,height:900});
await page.locator('#tr-app-trigger').focus();await page.keyboard.press('ArrowDown');assert(await page.locator('#tr-app-menu a').first().evaluate(e=>e===document.activeElement));await page.keyboard.press('Tab');assert(await page.locator('#tr-app-menu a').nth(1).evaluate(e=>e===document.activeElement));await page.keyboard.press('Tab');await page.keyboard.press('Tab');assert(await page.locator('#tr-app-menu').evaluate(e=>e.hidden));
await page.locator('#tr-app-trigger').click();await page.mouse.click(700,200);assert(await page.locator('#tr-app-menu').evaluate(e=>e.hidden));
await page.locator('#tr-app-trigger').click();await page.locator('#pp-settings-button').click();assert(await page.locator('#tr-app-menu').evaluate(e=>e.hidden));await page.locator('#tr-app-trigger').click();assert.equal(await page.locator('#pp-settings').isVisible(),false);await page.keyboard.press('Escape');
await page.setViewportSize({width:320,height:900});await page.locator('.tr-controls summary').click();await page.locator('#tr-app-trigger').click();assert.equal(await page.locator('.tr-controls').getAttribute('open'),null);await page.locator('.tr-controls summary').click();assert(await page.locator('#tr-app-menu').evaluate(e=>e.hidden));await page.keyboard.press('Escape');
await page.setViewportSize({width:1280,height:900});await page.locator('#pp-fullscreen').click();await page.waitForTimeout(100);assert(await page.evaluate(()=>!!document.fullscreenElement));assert.equal((await page.locator('.pp-brand').boundingBox()).height,60);await page.evaluate(()=>document.exitFullscreen());
const links=await page.evaluate(()=>TaalrouteAppMenu.apps.filter(a=>a.id!=='digibord'));for(const a of links){await page.route(a.url.split('#')[0],r=>r.fulfill({body:'<html><title>Navigation test</title>Destination</html>',contentType:'text/html'}));await page.locator('#tr-app-trigger').click();await page.locator(`[data-app="${a.id}"]`).click();await page.waitForURL(a.url);await page.goBack();await page.waitForSelector('#tr-app-trigger');assert.equal(page.url(),base);assert.equal(await page.locator('#tr-app-trigger').getAttribute('aria-expanded'),'false');}
await page.setViewportSize({width:390,height:160});await page.locator('#tr-app-trigger').click();assert(await page.locator('#tr-app-menu').evaluate(e=>e.scrollHeight>e.clientHeight&&e.getBoundingClientRect().bottom<=innerHeight));
assert.deepEqual(errors,[]);fs.writeFileSync('tests/artifacts/appmenu-measurements.json',JSON.stringify({status:'KANDIDAAT',results,checks:['keyboard','outside click','menu exclusivity','fullscreen','three same-tab links and browser Back','short-height scrolling','unique IDs','no console errors']},null,2));console.log('App menu: 20 layouts, keyboard, navigation, fullscreen and exclusivity passed.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
