const {chromium}=require('playwright'),assert=require('node:assert/strict'),server=require('../server.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});try{
const p=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const base=`http://127.0.0.1:${server.address().port}/Start-Praatpad.html`;await p.goto(base+'?kaart=Rotterdam-havenroute');await p.locator('#db-open-exercise').selectOption('direct');
for(const label of ['Wissel kaart','Speciale plekken','Vaknummers'])assert.ok(await p.locator('#db-map-tools .db-map-tool-label').getByText(label,{exact:true}).isVisible());
await p.locator('#db-quick-task').click();assert.equal(await p.locator('[data-catalog-shape]').count(),5);
for(const shape of ['circle','square','triangle','diamond']){await p.locator(`[data-catalog-shape="${shape}"]`).click();assert.equal(await p.locator(`[data-catalog-shape="${shape}"]`).getAttribute('aria-pressed'),'true');const size=await p.locator(`[data-catalog-shape="${shape}"] svg`).boundingBox();assert.equal(size.width,24);assert.equal(size.height,24);assert.ok(await p.locator('#pp-dialog .db-shape svg').count()>4);}
await p.locator('#pp-dialog h2').click();assert.equal(await p.locator('#pp-dialog').evaluate(e=>e.open),true);await p.mouse.click(5,100);assert.equal(await p.locator('#pp-dialog').evaluate(e=>e.open),false);
await p.locator('#db-open-maps').click();assert.equal(await p.locator('[data-choose-world]').count(),11);await p.locator('[data-choose-world="Rotterdam-havenroute"]').click();assert.equal(await p.locator('#pp-dialog').evaluate(e=>e.open),false);
await p.locator('#map-rules-button').click();assert.ok(await p.locator('.db-place-card').count()>0);await p.mouse.click(5,100);assert.equal(await p.locator('#pp-dialog').evaluate(e=>e.open),false);
const maps=await p.evaluate(()=>DigiBoardMaps.map(m=>m.id));for(const map of maps){await p.goto(base+'?kaart='+map);const toggle=p.locator('#world-route-help');if(await toggle.getAttribute('aria-pressed')!=='true')await toggle.click();assert.equal(await p.locator('#pp-tiles .pp-number').evaluateAll(es=>es.every(e=>{const c=getComputedStyle(e);return c.visibility==='visible'&&c.width==='26px'&&c.height==='26px'&&c.borderRadius==='50%'})),true,map);await toggle.click();assert.equal(await p.locator('#pp-tiles .pp-number').evaluateAll(es=>es.every(e=>(getComputedStyle(e).visibility==='visible')===(e.closest('.pp-tile').dataset.special==='true'))),true,map);}
assert.deepEqual(errors,[]);console.log('PASS equal shape icons, shape filters, backdrop dismissal, dedicated 11-world picker, circular number toggles on all worlds');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
