const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
const ctx=vm.createContext({lessonText:s=>s,esc:s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))});
vm.runInContext(source.slice(source.indexOf('function contentPromptHtml('),source.indexOf('function contentTaskText(')),ctx);
assert.equal(ctx.contentPromptHtml('Vertel dat je de reservering vandaag nog regelt. Gebruik er en voor zorgen.'),'Vertel dat je de reservering vandaag nog regelt. <span class="content-required">Gebruik <strong>er</strong> en <strong>voor zorgen</strong>.</span>');
assert.match(ctx.contentPromptHtml('Gebruik ‘zal’ of ‘zullen’.'),/<strong>‘zal’<\/strong> of <strong>‘zullen’<\/strong>/);
const bold=text=>Array.from(ctx.contentPromptHtml(text).matchAll(/<strong>(.*?)<\/strong>/g),m=>m[1]);
assert.deepEqual(bold('Gebruik zou: ‘Ik volg de cursus niet.’'),['zou']);
assert.deepEqual(bold('Gebruik er. Geef een reden.'),['er']);
assert.deepEqual(bold('Begin met Vandaag en gebruik er.'),['Vandaag','er']);
assert.deepEqual(bold('Maak de zin. Begin met ‘Er is vastgesteld’ en eindig met ‘is gevolgd’: procedure / is / gevolgd'),['‘Er is vastgesteld’','‘is gevolgd’']);
assert.deepEqual(bold('Reageer met ‘Er zijn redenen om’ en noem de twee redenen uit de situatie.'),['‘Er zijn redenen om’']);
assert.deepEqual(bold('Vul de juiste vorm van samenwerken in: Er wordt ___.'),['samenwerken']);
assert.deepEqual(bold('Geef antwoord met een vorm van zullen en moeten.'),['zullen','moeten']);
assert.deepEqual(bold('Doe een voorstel. Begin met Zullen we. Gebruik: naar buiten gaan.'),['Zullen we','naar buiten gaan']);
assert.deepEqual(bold('Vervang daar door er: Ik woon daar.'),['daar','er']);
assert.deepEqual(bold('Kies: thuis lezen of naar de bibliotheek gaan. Leg uit.'),['thuis lezen','naar de bibliotheek gaan']);
assert.deepEqual(bold('Welke hele zin met zouden klopt hier?'),['zouden']);
assert.deepEqual(bold('Wat betekent het woord ‘compact’ hier?'),['‘compact’']);
for(const text of ['Gebruik jij je telefoon?','Gebruik de informatie van de beheerder.','Wat denk je?','‘Hij zou er morgen zijn.’'])assert.equal(ctx.contentPromptHtml(text),ctx.esc(text));
assert.ok(!ctx.contentPromptHtml('Gebruik <img onerror="bad">.').includes('<img'));
console.log('PASS required words, starting/ending words, fill-in, choices, quoted terms, multiple instructions, unchanged text and HTML escaping.');
