const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),server=require('../server.cjs');
const {control}=require('./ui-controls.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});try{
 const p=await b.newPage({viewport:{width:1672,height:1149},reducedMotion:'no-preference'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:${server.address().port}/Praatpad.html?kaart=bos-bosroute`);fs.mkdirSync('tests/artifacts/forest-tree',{recursive:true});
 const state=()=>p.evaluate(()=>localStorage.getItem(DigiBoard.storageKey()));
 async function seed(pos){await p.evaluate(pos=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));Object.assign(d.settings,{motion:false,sound:false,pace:'dice'});d.session.players.forEach(x=>x.pos=pos);Object.assign(d.session,{active:0,selected:pos,started:true,finished:false});d.history=[];localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);},pos);await p.reload();}
 for(const size of [{width:788,height:889},{width:1672,height:1149}]){await p.setViewportSize(size);for(const n of [31,32,33,34,35,36]){await seed(n);const z=+(await p.locator('.pp-pawn[data-current=true]').evaluate(e=>getComputedStyle(e).zIndex));assert.equal(z,n===34||n===35?11:7,`tile ${n}, width ${size.width}`);if(size.width===1672){const r=await p.locator('#pp-map').boundingBox();await p.screenshot({path:`tests/artifacts/forest-tree/vak-${n}.png`,clip:{x:r.x+1380,y:r.y+300,width:292,height:440}});}}}
 async function sample(action){await p.evaluate(()=>{window.treeFrames=[];window.treeSampling=true;function frame(){const e=document.querySelector('.pp-pawn[data-current=true]'),m=document.getElementById('pp-map'),f=PraatpadWorld.fit(m.clientWidth,m.clientHeight);treeFrames.push({x:(parseFloat(e.style.left)-f.x)/f.scale,y:(parseFloat(e.style.top)-f.y)/f.scale,z:+getComputedStyle(e).zIndex});if(treeSampling)requestAnimationFrame(frame)}requestAnimationFrame(frame)});await action();await p.waitForFunction(()=>!document.getElementById('pp-roll').disabled);const frames=await p.evaluate(()=>{treeSampling=false;return treeFrames});for(const f of frames){if(f.x<1440||f.y<370||f.y>690)continue;assert.equal(f.z,f.y>527&&f.y<655?11:7,JSON.stringify(f));}assert(frames.some(f=>f.y<497&&f.y>378));assert(frames.some(f=>f.y>557&&f.y<620));return frames;}
 await seed(30);await p.evaluate(()=>Math.random=()=>.999);await sample(()=>p.locator('#pp-roll').click());assert.equal(JSON.parse(await state()).session.players[0].pos,36);
 const saved=await state();assert.deepEqual(await p.evaluate(()=>DigiBoardMap.depthRoutes.tree),{from:31,exits:[36]});
 for(const backwards of [false,true]){if(backwards)await p.evaluate(()=>DigiBoardMap.depthRoutes.tree={from:36,exits:[31]});await control(p,'#map-rules-button','click');await sample(()=>p.locator('[data-preview-depth="tree"]').click());assert.equal(await state(),saved);}
 assert.deepEqual(errors,[]);console.log('PASS forest tree: 31–33 behind, 34–35 in front, 36 clear; two sizes, real roll, forward/reverse preview, saved state preserved');
}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
