const {control,reveal,conceal}=require('./ui-controls.cjs');
const {chromium}=require('playwright'),assert=require('assert');
const fs=require('node:fs'),path=require('node:path'),server=require('../server.cjs');fs.mkdirSync(path.join(__dirname,'artifacts'),{recursive:true});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true}),p=await b.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>{errors.push(e.stack);console.log(e.stack)});
const base='http://127.0.0.1:'+server.address().port+'/Praatpad.html';await p.goto(base);
for(const [id,count] of [['Rotterdam-havenroute',40],['amsterdam-grachtenroute',46],['utrecht-werfroute',46],['dorp-boomgaardroute',55],['kust-duinroute',32],['bos-bosroute',53]]){
 await p.goto(base+'?kaart='+id);assert.equal(await p.locator('[data-node]').count(),count);
 const failures=await p.evaluate(()=>{const R=PraatpadRoutes,data=JSON.parse(document.getElementById('pp-content').textContent),boards=globalThis.PraatpadVariations?PraatpadVariations.catalog.map(v=>({id:v.id,cityArtwork:true,layout:{shape:v.id,mirror:false,connections:v.connections}})):[{cityArtwork:!!globalThis.DigiBoardMap,layout:{shape:'snake',mirror:false,connections:globalThis.PraatpadWorld?.connections||[]}}];const bad=[];for(const board of boards)for(const c of board.layout.connections)for(const to of c.exits){const g=R.routeGeometry(board,1024,600,c,to);if(!g.points.flat().every(Number.isFinite))bad.push(c.id);if(g.layout.points.length!==data.tasks.length+2)bad.push(c.id+' count');}return bad;});assert.deepEqual(failures,[]);
}
await p.goto(base+'?kaart=Rotterdam-havenroute');
async function form(v){await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-dice').click();await p.locator('#pp-dice-style').selectOption(v);await p.locator('#pp-settings-close').click();}
async function state(){return p.evaluate(()=>JSON.parse(localStorage.getItem(DigiBoard.storageKey())));}
async function map(v){await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-board').click();await p.locator('#db-board-map').selectOption(v);await p.waitForURL('**kaart='+v);}
await form('verbs');await p.getByRole('button',{name:'Werp alle negen',exact:true}).click();await p.getByRole('button',{name:'Werp alle negen',exact:true}).waitFor();let picture=(await state()).session.pictureDice;
await map('Rotterdam-havenroute');await form('verbs');assert.deepEqual((await state()).session.pictureDice,picture);await form('wordgame');assert(await p.locator('#pp-wordgame').isVisible());await p.screenshot({path:path.join(__dirname,'artifacts/woordspel.png')});await form('numbers');
for(const size of [{width:1366,height:768},{width:1920,height:1080},{width:1024,height:768}]){await p.setViewportSize(size);const dims=await p.evaluate(()=>({h:document.documentElement.scrollHeight,w:document.documentElement.scrollWidth,ih:innerHeight,iw:innerWidth}));assert(dims.h<=dims.ih&&dims.w<=dims.iw,JSON.stringify(dims));}
// Seed deterministic landings through the saved lesson format, then use the real Roll and Undo buttons.
for(const [from,to] of [[13,12],[15,20],[28,21]]){
 await p.evaluate(({from})=>{const k=DigiBoard.storageKey(),d=JSON.parse(localStorage.getItem(k));d.settings.diceStyle='numbers';d.settings.pace='dice';d.settings.motion=true;d.session.players.forEach(p=>p.pos=from-1);d.session.active=0;d.session.started=false;d.session.selected=from-1;d.session.travel={uses:[],keys:[],visits:[],pending:null,last:null};localStorage.setItem(k,JSON.stringify(d));DigiBoard.saveShared(d);},{from});await p.reload();await p.evaluate(()=>Math.random=()=>0);await p.locator('#pp-roll').click();await p.waitForFunction(()=>!document.getElementById('pp-roll').disabled);assert.equal((await state()).session.players[0].pos,to);await p.reload();assert.equal((await state()).session.players[0].pos,to);await control(p,'#pp-back','click');assert.equal((await state()).session.players[0].pos,from-1);
}
await map('utrecht-werfroute');await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-board').click();await p.locator('#pp-pace').selectOption('all');await p.locator('#pp-settings-close').click();await p.locator('#pp-roll').click();await p.waitForFunction(()=>!document.getElementById('pp-roll').disabled);assert.equal((await state()).session.players[0].pos,1);await map('Rotterdam-havenroute');assert.equal((await state()).session.players[0].pos,27);
await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-sound').click();await p.locator('#pp-motion').uncheck();await p.locator('#pp-settings-close').click();await control(p,'#map-rules-button','click');await p.getByRole('button',{name:'Langs de boom',exact:true}).click();await p.waitForTimeout(800);await p.screenshot({path:path.join(__dirname,'artifacts/boom-beweging.png')});await p.waitForFunction(()=>!document.getElementById('pp-roll').disabled);assert.equal((await state()).session.players[0].pos,27);
assert.deepEqual(errors,[]);await b.close();server.close();console.log('PASS shared dice state, sentence game, six maps, full screen, special landings, undo, reload, independent map progress, live tree preview');})().catch(e=>{console.error(e);process.exit(1)});
