const {chromium}=require('playwright'),assert=require('node:assert/strict'),server=require('../server.cjs'),fs=require('node:fs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port+'/Start-Praatpad.html';await p.goto(base+'?kaart=stad24');assert.equal(await p.evaluate(()=>DigiBoard.mapId),'Rotterdam-havenroute');assert.equal(await p.locator('#db-board-map option').count(),11);
await p.locator('[data-node="1"]').click();await p.locator('#pp-use-task').click();
const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem(DigiBoard.storageKey())));
async function seed(fn){await p.evaluate(fn);await p.reload();}
await seed(()=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));d.roster=Array.from({length:20},(_,i)=>({id:'c'+i,name:'Cursist '+(i+1),present:true}));d.session.people=d.roster.map(x=>x.id);d.session.players=DigiBoardLearning.players('class',d.session.people);d.session.mode='class';d.session.active=0;d.session.selected=0;d.session.started=false;d.history=[];d.previous=[];Object.assign(d.settings,{motion:true,sound:false,pace:'all',workForm:'spotlight'});localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);});
async function roll(){await p.locator('#pp-roll').click();await p.waitForFunction(()=>!document.querySelector('#pp-roll').disabled);}
await roll();let d=await state();assert.equal(d.settings.workForm,'spotlight');assert.equal(d.session.speakerQueue.order.length,20);const order=[...d.session.speakerQueue.order];assert.equal(new Set(order).size,20);assert.equal(d.session.speakerQueue.current,order[0]);assert.match(await p.locator('#pp-speaker').textContent(),/Hardop: Cursist/);
await p.locator('#pp-back').click();assert.deepEqual((await state()).session.speakerQueue.order,order);await roll();assert.equal((await state()).session.speakerQueue.current,order[0]);await p.reload();await roll();assert.equal((await state()).session.speakerQueue.current,order[1]);await p.locator('#pp-back').click();assert.equal((await state()).session.speakerQueue.current,order[0]);await roll();assert.equal((await state()).session.speakerQueue.current,order[1]);
for(let i=2;i<20;i++){await roll();assert.equal((await state()).session.speakerQueue.current,order[i]);}await roll();assert.equal((await state()).session.speakerQueue.current,order[0]);await p.screenshot({path:__dirname+'/artifacts/klassikaal-een-spreker.png'});
await p.locator('#db-open-maps').click();for(const level of ['A0','A1','A2','B1']){await p.locator('#db-learning-level').selectOption(level);await p.locator('#pp-settings-close').click();assert.match(await p.locator('#pp-task-label').textContent(),/VAK/);assert.equal(await p.locator('#pp-practice-hint').textContent(),'');await p.locator('#db-open-maps').click();}
await p.locator('#db-work-form').selectOption('individual');for(const n of [5,10,20]){await p.locator('#db-pawn-mode').selectOption('teams');await p.locator('#db-pawn-count').selectOption(String(n));await p.locator('#db-apply-pawns').click();assert.equal((await state()).session.players.length,n);assert.equal(new Set((await state()).session.players.flatMap(x=>x.members)).size,20);}
await p.locator('#db-pawn-mode').selectOption('individual');await p.locator('#db-apply-pawns').click();assert.equal((await state()).session.players.length,20);await p.locator('#db-turn-style').selectOption('parallel');await p.locator('#pp-settings-close').click();const before=(await state()).session.players.map(x=>x.pos);await roll();d=await state();assert.equal(d.session.roundResults.length,20);assert.deepEqual(d.session.players.map(x=>x.pos),before.map(x=>x+1));await p.keyboard.press('Escape');await p.locator('#pp-back').click();assert.deepEqual((await state()).session.players.map(x=>x.pos),before);

// A separate random throw for every pawn, then two pending route choices with reload.
await seed(()=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));d.settings.pace='dice';d.session.players.forEach(x=>x.pos=0);d.session.selected=0;d.session.travel={uses:[],keys:[],visits:[],pending:null,last:null};delete d.session.batch;d.history=[];localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);});await p.evaluate(()=>{let n=0;Math.random=()=>((n++%6)+.1)/6;});await roll();assert.deepEqual((await state()).session.roundResults.map(r=>r.roll),Array.from({length:20},(_,i)=>i%6+1));await p.keyboard.press('Escape');
await p.goto(base+'?kaart=polder-slotenroute');await p.locator('[data-node="1"]').click();await p.locator('#pp-use-task').click();
await seed(()=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));d.session.people=d.session.people.slice(0,2);d.session.players=DigiBoardLearning.players('individual',d.session.people);d.session.players.forEach(x=>x.pos=14);Object.assign(d.session,{mode:'individual',active:0,selected:14,started:false,travel:{uses:[],keys:[],visits:[],pending:null,last:null}});delete d.session.batch;d.history=[];d.previous=[];Object.assign(d.settings,{pace:'dice',turnStyle:'parallel',workForm:'individual'});localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);});await p.evaluate(()=>Math.random=()=>0);await p.locator('#pp-roll').click();await p.locator('[data-travel-choice="15"]').waitFor();await p.reload();await p.evaluate(()=>Math.random=()=>0);await p.locator('[data-travel-choice="15"]').click();await p.locator('[data-travel-choice="47"]').waitFor();await p.locator('[data-travel-choice="47"]').click();await p.waitForFunction(()=>!document.querySelector('#pp-roll').disabled);assert.deepEqual((await state()).session.players.map(x=>x.pos),[15,47]);assert.equal((await state()).session.roundResults.length,2);await p.keyboard.press('Escape');await p.locator('#pp-back').click();assert.deepEqual((await state()).session.players.map(x=>x.pos),[14,14]);
// Every task in every visible world is covered at all four levels.
const maps=await p.evaluate(()=>DigiBoardMaps);for(const m of maps){await p.goto(base+'?kaart='+m.id);const missing=await p.evaluate(()=>JSON.parse(document.querySelector('#pp-content').textContent).tasks.filter(t=>!DigiBoardLessonsContent.mapping[t.title]).map(t=>t.title));assert.deepEqual(missing,[],m.id);}
const audit=await p.evaluate(()=>{const c=DigiBoardLessonsContent,issues=[];for(const [title,key]of Object.entries(c.mapping))if(!c.packs[key])issues.push(title);for(const [key,pack]of Object.entries(c.packs))for(const level of DigiBoardLearning.levels){const r=pack[level];for(const f of ['grammar','instruction','model','partner','criterion','support'])if(!r?.[f])issues.push(key+level+f);for(const form of Object.keys(DigiBoardLearning.forms)){const t=DigiBoardLearning.adapt({title:Object.keys(c.mapping).find(t=>c.mapping[t]===key)},{learningLevel:level,workForm:form},{mode:'class'});if(t.level!==level||!t.grammar||!t.help)issues.push(key+form);}}for(const [title,pack]of Object.entries(c.contexts||{}))for(const [level,r]of Object.entries(pack)){if(!r.instruction||!r.model||!r.grammar)issues.push(title+level);if(DigiBoardLearning.adapt({title},{learningLevel:level,workForm:'individual'},{mode:'class'}).model!==r.model)issues.push(title+' context');}return{issues,scenarios:Object.keys(c.packs).length*4,contextVariants:Object.keys(c.contexts).length*4};});assert.deepEqual(audit.issues,[]);assert.equal(audit.scenarios,112);
await p.locator('#db-open-maps').click();await p.screenshot({path:__dirname+'/artifacts/lesvormen.png'});await p.locator('#pp-settings-close').click();for(const size of [{width:1024,height:768},{width:1366,height:768},{width:1920,height:1080}]){await p.setViewportSize(size);assert.ok(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth));}assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/artifacts/learning-report.json',JSON.stringify({passed:true,...audit,checks:['11 worlds and legacy URL fallback','speaker order, reload and undo','four levels','5/10/20 group pawns','20 individual pawns','parallel round and undo','desktop viewports']},null,2));console.log('PASS learning modes, 112 scenarios, speaker queue, 20 pawns, parallel round and undo');}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
