const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),server=require('../server.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port+'/Start-Praatpad.html';await p.goto(base+'?kaart=dorp-boomgaardroute');
const matrix=await p.evaluate(()=>{const d=DigiBoardRouteLessons,source=JSON.parse(document.querySelector('#pp-fl-data').textContent),bad=[];for(const r of d.routes){const cards=d.cards.filter(c=>c.routeId===r.id);if(cards.length!==48)bad.push(r.id+' count');for(const f of d.families)if(cards.filter(c=>c.familyId===f.id).length!==8)bad.push(r.id+f.id);for(const a of source.actions){const t=cards.find(c=>c.actionId===a.id);if(t&&/met hulp|met begeleiding|Bedenk wat je zelf|De docent doet/i.test(t.instruction))bad.push(a.id+' learner wording');if(!t||t.preparatory!==(Number(r.id.at(-1))<a.independentFrom))bad.push(a.id+' preparation');for(const key of ['instruction','grammar','model','partner','teacher','criterion','retry'])if(!t?.[key])bad.push(a.id+key);}}return{bad,count:d.cards.length,ids:new Set(d.cards.map(c=>c.id)).size,routes:d.routes.map(r=>({label:r.label,tasks:d.cards.filter(c=>c.routeId===r.id).length}))};});assert.deepEqual(matrix.bad,[]);assert.equal(matrix.count,192);assert.equal(matrix.ids,192);
await p.locator('#db-open-maps').click();assert.deepEqual(await p.locator('#db-learning-level option').allTextContents(),['A0 → A1','A1 → A1+','A1 → A2','A2 → B1']);
for(const [level,route]of[['A0','route-0'],['A1','route-1'],['A2','route-2'],['B1','route-3']]){await p.locator('#db-learning-level').selectOption(level);await p.locator('#db-lesson-catalog').click();assert.equal(await p.locator('[data-use-lesson]').count(),48);await p.locator('#db-catalog-family').selectOption('begrip');assert.equal(await p.locator('[data-use-lesson]').count(),8);await p.locator('[data-use-lesson="geef-door"]').click();assert.match(await p.locator('#pp-task-title').textContent(),/Geef door/);assert.equal(await p.locator('#pp-role-b').textContent(),'Informatie');assert.equal(await p.locator('#pp-partner').textContent(),await p.evaluate(route=>DigiBoardRouteLessons.cards.find(c=>c.routeId===route&&c.actionId==='geef-door').input,route));assert.match(await p.locator('[data-node="1"]').getAttribute('aria-label'),/Geef door/);await p.locator('#db-lesson-support').click();assert.match(await p.locator('#pp-dialog-content').textContent(),/Oefengegevens/);assert.match(await p.locator('#pp-dialog-content').textContent(),/Grammatica/);await p.keyboard.press('Escape');await p.reload();assert.match(await p.locator('#pp-task-title').textContent(),/Geef door/);await p.locator('#db-open-maps').click();}
await p.locator('#pp-settings-close').click();await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-didactics').click();await p.locator('#pp-fl-level').selectOption('route-1');await p.locator('[data-family="regelen"]').click();await p.locator('[data-action="spreek-af"]').click();await p.locator('#db-use-didactic').click();assert.match(await p.locator('#pp-task-title').textContent(),/Spreek af/);assert.match(await p.locator('#pp-task-label').textContent(),/VAK/);await p.locator('#db-lesson-support').click();assert.match(await p.locator('#pp-dialog-content').textContent(),/Voorbereidend/);await p.keyboard.press('Escape');
// All cards actually adapt at all routes; existing role forms keep the same goal.
const runtime=await p.evaluate(()=>{const C=DigiBoardRouteLessons,bad=[];for(const r of C.routes)for(let n=1;n<=48;n++)for(const workForm of Object.keys(DigiBoardLearning.forms)){const base={id:'t'+n,number:n,title:'Legacy'},t=DigiBoardLearning.adapt(base,{learningLevel:r.legacyLevel,workForm},{mode:'class'});if(t.routeId!==r.id||!t.grammar||!t.model||!t.familyId)bad.push(r.id+n+workForm);if(['individual','classroom','spotlight'].includes(workForm)&&/Wissel.*rol/.test(t.partner))bad.push('mixed '+workForm);}return bad;});assert.deepEqual(runtime,[]);
await p.locator('#db-open-maps').click();await p.locator('#db-learning-level').selectOption('B1');await p.locator('#db-work-form').selectOption('groups');await p.locator('#db-lesson-catalog').click();await p.locator('[data-use-lesson="geef-door"]').click();assert.match(await p.locator('#pp-instruction').textContent(),/A leest.*B vertelt.*C.*Wissel/);assert.match(await p.locator('#pp-partner').textContent(),/11.00 uur/);await p.screenshot({path:__dirname+'/artifacts/leerroutes-groepsopdracht.png'});
for(const size of[{width:1024,height:768},{width:1366,height:768},{width:1920,height:1080}]){await p.setViewportSize(size);assert.ok(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth));}
await p.locator('#db-open-maps').click();await p.locator('#db-lesson-catalog').click();await p.screenshot({path:__dirname+'/artifacts/leerroutes-catalogus.png'});await p.keyboard.press('Escape');await p.locator('#pp-settings-close').click();await p.locator('#db-lesson-support').click();await p.screenshot({path:__dirname+'/artifacts/leerroutes-docent.png'});assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/artifacts/leerroutes-report.json',JSON.stringify({passed:true,...matrix,checks:['catalogue48/filter8','four explicit routes','pick task without moving pawn','reload','didactics-to-board','guided tasks remain guided','192 tasks x5 forms','three active roles','viewports'],errors},null,2));console.log('PASS 192 route tasks, six families, grammar, catalogue, didactics-to-board, persistence and five work forms');}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
