const {chromium}=require('playwright'),assert=require('node:assert'),fs=require('node:fs'),path=require('node:path'),server=require('../server.cjs');
const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true});try{const p=await browser.newPage({viewport:{width:1600,height:1000},reducedMotion:'reduce'}),errors=[],assets=[],report={maps:[],animations:[]};p.on('pageerror',e=>errors.push(e.stack));p.on('response',r=>{if(r.status()>=400)assets.push(r.url());});const base='http://127.0.0.1:'+server.address().port+'/Start-Praatpad.html';
async function state(){return p.evaluate(()=>JSON.parse(localStorage.getItem(DigiBoard.storageKey())));}
async function open(id){await p.goto(base+'?kaart='+id);await p.locator('#pp-scenery').evaluate(i=>i.decode());if(!await state()){await p.locator('[data-node="1"]').click();await p.locator('#pp-use-task').click();}}
async function setup(pos,motion=true,pace='dice'){await p.evaluate(({pos,motion,pace})=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));Object.assign(d.settings,{motion,pace,diceStyle:'numbers',sound:false});d.session.players.forEach(x=>x.pos=pos);d.session.active=0;d.session.selected=pos;d.session.finished=false;d.session.travel={uses:[],keys:[],visits:[],pending:null,last:null};d.history=[];localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);},{pos,motion,pace});await p.reload();await p.locator('#pp-scenery').evaluate(i=>i.decode());}
async function roll(n){await p.evaluate(n=>Math.random=()=>((n-1)+.1)/6,n);await p.locator('#pp-roll').click();}
async function done(){await p.waitForFunction(()=>!document.querySelector('#pp-roll').disabled,{},{timeout:20000});}
await open('Rotterdam-havenroute');const maps=await p.evaluate(()=>DigiBoardMaps);assert.equal(maps.length,11);
for(const m of maps){await open(m.id);assert.equal(await p.locator('[data-node]').count(),m.count,m.id);assert.equal(await p.locator('#db-board-map option').count(),11);if(!await p.evaluate(()=>DigiBoardMap?.special).catch(()=>false))continue;
 const cs=await p.evaluate(()=>PraatpadWorld.connections),g=await p.evaluate(()=>({a:PraatpadWorld.anchors,l:PraatpadWorld.legs}));assert.equal(g.a.length,m.count+2);for(let i=0;i<g.l.length;i++){assert.deepEqual(g.l[i][0],g.a[i]);assert.deepEqual(g.l[i].at(-1),g.a[i+1]);}
 const checks=[];for(const c of cs){for(const to of c.exits){await setup(c.from-1);await roll(1);if(c.optional||['hill_choice','beam_choice'].includes(c.type)){await p.locator(`[data-travel-choice="${to}"]`).waitFor();await p.reload();await p.locator(`[data-travel-choice="${to}"]`).click();}await done();assert.equal((await state()).session.players[0].pos,to,m.id+' '+c.id);await p.reload();assert.equal((await state()).session.players[0].pos,to);const title=await p.locator('#pp-task-title').textContent(),task=await p.evaluate(to=>(()=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey())),t=DigiBoardLearning.adapt(JSON.parse(document.querySelector('#pp-content').textContent).tasks[to-1],d.settings,d.session);return t.title;})(),to);assert.equal(title,task);await p.locator('#pp-back').click();assert.equal((await state()).session.players[0].pos,c.from-1);checks.push(c.from+'→'+to);}
 if(c.optional){await setup(c.from-1);await roll(1);await p.locator(`[data-travel-choice="${c.from}"]`).click();await done();assert.equal((await state()).session.players[0].pos,c.from);}
 await setup(c.from-1,true,'all');await roll(1);await done();assert.equal((await state()).session.players[0].pos,c.from);assert.equal(await p.locator('[data-travel-choice]:visible').count(),0);
 if(c.from<m.count&&!cs.some(x=>x.from===c.from+1)){await setup(c.from-1);await roll(2);await done();assert.equal((await state()).session.players[0].pos,c.from+1);}
 }
 await setup(m.count);await roll(6);await done();assert.equal((await state()).session.players[0].pos,m.count+1);report.maps.push({id:m.id,checks});console.log('PASS',m.id,checks.join(', '));
}
await p.emulateMedia({reducedMotion:'no-preference'});
for(const cfg of [{id:'amsterdam-grachtenroute',from:18,to:23,phase:'tunnelPhase',hidden:'hidden'},{id:'bos-bosroute',from:49,to:46,phase:'tunnelPhase',hidden:'hidden'},{id:'polder-slotenroute',from:15,to:47,phase:'ferryPhase',hidden:'sailing',choice:true},{id:'fantasie-eilanden',from:8,to:26,phase:'portalPhase',hidden:'hidden'},{id:'ruimte-maanroute',from:14,to:25,phase:'beamPhase',hidden:'hidden',choice:true}]){await open(cfg.id);await setup(cfg.from-1,false);await roll(1);if(cfg.choice)await p.locator(`[data-travel-choice="${cfg.to}"]`).click();await p.waitForFunction(({phase,hidden})=>document.querySelector('#praatpad-board').dataset[phase]===hidden,cfg,{timeout:15000});if(cfg.hidden==='hidden')assert.equal(await p.locator('.pp-pawn[data-current="true"]').evaluate(e=>+getComputedStyle(e).opacity),0);await p.screenshot({path:path.join(out,cfg.id+'-beweging.png')});await done();assert.equal((await state()).session.players[0].pos,cfg.to);await p.locator('#pp-back').click();assert.equal((await state()).session.players[0].pos,cfg.from-1);
 // Cancel while actually travelling, then wait beyond the original duration.
 await setup(cfg.from-1,false);await roll(1);if(cfg.choice)await p.locator(`[data-travel-choice="${cfg.to}"]`).click();await p.waitForFunction(({phase,hidden})=>document.querySelector('#praatpad-board').dataset[phase]===hidden,cfg,{timeout:15000});await p.locator('#pp-back').click();await p.waitForTimeout(7000);assert.equal((await state()).session.players[0].pos,cfg.from-1);assert.ok(!await p.locator('#pp-roll').isDisabled());report.animations.push(cfg.id);console.log('PASS animation and cancel',cfg.id);}
// Select through the real shared picker and verify independent map progress and shared settings.
await open('ruimte-maanroute');await setup(12,true);await p.locator('#db-open-maps').click();assert.ok(await p.locator('#db-board-map').isVisible());await p.screenshot({path:path.join(out,'alle-kaarten.png')});await p.locator('#db-board-map').selectOption('amsterdam-grachtenroute');await p.waitForURL('**kaart=amsterdam-grachtenroute');await setup(20,true);await p.locator('#db-open-maps').click();await p.locator('#db-board-map').selectOption('ruimte-maanroute');await p.waitForURL('**kaart=ruimte-maanroute');assert.equal((await state()).session.players[0].pos,12);assert.equal((await state()).settings.motion,true);report.independentProgress=true;
await setup(13,false);const saved=JSON.stringify((await state()).session);for(const to of[2,25]){await p.locator('#map-rules-button').click();await p.locator(`[data-preview-route="transportstraal"][data-preview-to="${to}"]`).click();await p.waitForFunction(()=>document.querySelector('#praatpad-board').dataset.beamPhase==='hidden');await done();assert.equal(JSON.stringify((await state()).session),saved);}report.choicePreviews=true;
for(const size of[{width:1024,height:768},{width:1366,height:768},{width:1920,height:1080}]){await p.setViewportSize(size);const dims=await p.evaluate(()=>({h:document.documentElement.scrollHeight,w:document.documentElement.scrollWidth,ih:innerHeight,iw:innerWidth}));assert.ok(dims.h<=dims.ih&&dims.w<=dims.iw,JSON.stringify(dims));}report.viewport=true;
await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-dice').click();await p.locator('#pp-dice-style').selectOption('verbs');await p.locator('#pp-settings-close').click();assert.ok(await p.getByRole('button',{name:'Werp alle negen',exact:true}).isVisible());assert.equal(await p.locator('.db-map-layer:visible').count(),0);await p.locator('#pp-settings-button').click();await p.locator('#pp-nav-dice').click();await p.locator('#pp-dice-style').selectOption('wordgame');await p.locator('#pp-settings-close').click();assert.ok(await p.locator('#pp-wordgame').isVisible());report.sharedGameForms=true;
assert.deepEqual(errors,[]);assert.deepEqual(assets,[]);report.errors=errors;fs.writeFileSync(path.join(out,'map-family-report.json'),JSON.stringify(report,null,2));console.log('PASS map family, shared picker, separate progress, previews, no asset/runtime errors');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
