const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const ctx={crypto:webcrypto,Date};vm.createContext(ctx);for(const f of ['opdrachtenmatrix-data.js','kaartvormen.js','opdrachtenmatrix.js','zinnenspel.js'])vm.runInContext(fs.readFileSync(__dirname+'/../Lessen/'+f,'utf8'),ctx);const M=ctx.DigiBoardMatrix,B=M.bank,S=ctx.DigiBoardSentence;
assert.deepEqual(JSON.parse(JSON.stringify(B)),JSON.parse(fs.readFileSync(__dirname+'/../Lessen/opdrachtenmatrix.json')));
assert.equal(B.cards.length,960);assert.equal(new Set(B.cards.map(t=>t.id)).size,960);
for(const r of B.routes){const rows=B.cards.filter(c=>c.routeId===r.id);assert.equal(rows.length,240);assert.equal(new Set(rows.map(c=>c.instruction+'|'+c.input)).size,240);for(const sh of B.shapes){assert.equal(rows.filter(c=>c.shape===sh.id).length,60);for(const topic of B.topics)assert.equal(rows.filter(c=>c.shape===sh.id&&c.topic===topic.id).length,10);}}
for(const c of B.cards){for(const k of ['instruction','support','model','grammar','retry','criterion'])assert.ok(c[k]?.trim(),c.id+' '+k);assert.ok(!/undefined|\bNaN\b|\[object|Vraag dinsdag|stel gerust|Ik kies:|Ik kies vol\./i.test(c.instruction+' '+c.input+' '+c.model),c.id);assert.notEqual(c.instruction,c.model,c.id);}
const base={id:'t1',number:1,type:'vertel'},content={tasks:[base]};const make=(level='A0',groupId='group1')=>({settings:{learningLevel:level},session:{groupId,people:['a'],players:[{id:'p',pos:0}],active:0,turn:0,board:{tasks:['t1']}}});
for(const r of B.routes)for(const sh of B.shapes){const d=make(r.legacyLevel);let last;for(let cycle=0;cycle<2;cycle++){const seen=new Set();for(let i=0;i<60;i++){const q=M.pick(d,sh.id,last?[last]:[]);assert.ok(!seen.has(q.id),r.id+sh.id+' repeated before exhaustion');seen.add(q.id);M.consume(d,q);last=q.id;}assert.equal(seen.size,60);}}
let d=make();M.ensure(d,content);const before=JSON.stringify(d.session.matrix);M.ensure(d,content);assert.equal(JSON.stringify(d.session.matrix),before);const reloaded=JSON.parse(JSON.stringify(d));M.ensure(reloaded,content);assert.equal(JSON.stringify(reloaded.session.matrix),before);
d.session.turn++;d.session.players[0].pos=1;d.session.travel={pending:{id:'tunnel'}};M.ensure(d,content);assert.equal(d.session.matrix.awaiting,true);assert.equal(Object.keys(M.progress(d).used).length,0);d.session.travel.pending=null;M.ensure(d,content);assert.equal(d.session.matrix.awaiting,false);assert.equal(M.progress(d).used['route-0/circle'].length,1);const first=M.task(base,d.settings,d.session);assert.equal(first.id,'t1');assert.notEqual(first.lessonId,'t1');M.another(d,base);assert.notEqual(M.task(base,d.settings,d.session).lessonId,first.lessonId);
const d2=make('A0','group2');d2.matrixProgress=d.matrixProgress;assert.equal(Object.keys(M.progress(d2).used).length,0);
// Separate pawn tasks remain stable even when two pawns share a square.
d.session.players.push({id:'p2',pos:1});d.session.active=1;d.session.turn++;M.ensure(d,content);const p2=M.task(base,d.settings,d.session).lessonId;d.session.active=0;const p1=M.task(base,d.settings,d.session).lessonId;assert.notEqual(p1,p2);d.session.active=1;assert.equal(M.task(base,d.settings,d.session).lessonId,p2);
assert.equal(M.validProgress({version:1,groups:{bad:{used:{},recent:[]}}}),false);assert.equal(M.validSession({version:1}),false);
for(const [map,shapes]of Object.entries(ctx.DigiBoardTileShapes)){assert.ok(shapes.length>20,map);for(let i=0;i<shapes.length;i++)assert.equal(M.shape({number:i+1},map),shapes[i]);}
// Explicit irregular and separable Dutch forms, including auxiliary selection.
for(const [person,verb,tense,answer]of [[0,'eten','past','Ik at een appel.'],[1,'wachten','present','Jij wacht op de bus.'],[3,'opstaan','present','Wij staan om zeven uur op.'],[4,'meenemen','past','Jullie namen een tas mee.'],[5,'lopen','perfect','Zij zijn naar de winkel gelopen.'],[2,'komen','perfect','Zij is naar de les gekomen.'],[0,'fietsen','perfect','Ik ben naar school gefietst.']])assert.equal(S.answer({person,verb,tense}),answer);
let count=0;for(let person=0;person<6;person++)for(const v of S.verbs)for(const t of S.tenses){const answer=S.answer({person,verb:v.id,tense:t.id});assert.ok(answer.endsWith('.')&&!/undefined|NaN/.test(answer),answer);count++;}assert.equal(count,432);
const ss=S.state(make());assert.equal(ss.options.tenses.join(','),'present');const used=new Set();for(let i=0;i<18;i++){const q=S.draw(ss),key=JSON.stringify(q);assert.ok(!used.has(key));used.add(key);}assert.equal(used.size,18);assert.equal(S.valid(ss),true);
fs.mkdirSync(__dirname+'/artifacts',{recursive:true});fs.writeFileSync(__dirname+'/artifacts/matrix-content-report.json',JSON.stringify({passed:true,cards:960,perRoute:240,perShapePerRoute:60,contexts:60,sentenceCombinations:count,checks:['unique cards, complete fields, four shapes','two full no-repeat cycles per route and shape','stable reload','pending tunnel choice','group isolation','separate pawn assignments','Dutch irregular and separable verbs']},null,2));console.log('PASS matrix: 960 cards, 16 decks without repeats, 432 sentence combinations');
require('./language-review.cjs');
