const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{execFileSync}=require('child_process'),server=require('../server.cjs'),{control}=require('./ui-controls.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await b.newPage({viewport:{width:1600,height:1000},reducedMotion:'no-preference'}),errors=[],report=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.url())});const base=`http://127.0.0.1:${server.address().port}/Praatpad.html`,out=path.join(__dirname,'artifacts','nieuwe-kaarten');fs.mkdirSync(out,{recursive:true});
async function state(){return p.evaluate(()=>JSON.parse(localStorage.getItem(DigiBoard.storageKey())))}
async function setup(pos,motion=false){await p.evaluate(({pos,motion})=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));d.settings.motion=motion;d.settings.sound=false;d.settings.pace='dice';d.settings.turnStyle='turns';d.session.players.forEach(x=>x.pos=pos);d.session.active=0;d.session.selected=pos;d.session.finished=false;d.history=[];localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);},{pos,motion});await p.reload();await p.locator('#pp-scenery').evaluate(e=>e.decode())}
async function done(){await p.waitForFunction(()=>!document.querySelector('#pp-roll').disabled,null,{timeout:20000})}
try{for(const [id,count]of [['markt-pleinroute',12],['station-perronroute',16],['pool-ijsroute',30]]){
await p.goto(base+'?kaart='+id);await p.locator('#pp-scenery').evaluate(e=>e.decode());await p.locator('[data-node="1"]').click();await p.locator('#pp-use-task').click();await setup(0);
assert.equal(await p.locator('[data-node]').count(),count);assert.equal(await p.locator('.new-world-tiles').count(),0);assert.equal(await p.locator('#praatpad-board').getAttribute('data-painted-route'),'true');assert((await p.locator('#pp-scenery').getAttribute('src')).includes('-speelroute.png')); assert.equal(await p.locator('#db-board-map option').count(),14);
const audit=await p.evaluate(()=>{const W=PraatpadWorld,issues=[],shapes=DigiBoardTileShapes[DigiBoardMap.id];for(let i=0;i<W.anchors.length-1;i++)for(const reverse of[false,true]){const a=reverse?i+1:i,b=reverse?i:i+1;let prior;for(let n=0;n<=1000;n++){const q=W.pose(a,b,n/1000);if(q.point.some(v=>!Number.isFinite(v)))issues.push('invalid');if(n===0&&Math.hypot(...q.point.map((v,k)=>v-W.anchors[a][k]))>.01)issues.push('start');if(n===1000&&Math.hypot(...q.point.map((v,k)=>v-W.anchors[b][k]))>.01)issues.push('end');if(prior&&q.opacity>0&&prior.opacity>0&&Math.hypot(...q.point.map((v,k)=>v-prior.point[k]))>12)issues.push('jump');prior=q;}}for(const x of W.passages){if(x.kind==='tunnel'){if(W.pose(x.from,x.to,.5).opacity!==0)issues.push('visible underground');for(const t of[.01,.18,.84,.99])if(W.pose(x.from,x.to,t).depth!==11)issues.push('outside behind rim');}if(x.kind==='lift'){const a=W.pose(x.from,x.to,.3),b=W.pose(x.from,x.to,.7);if(a.point[0]!==b.point[0]||a.point[1]<=b.point[1])issues.push('not vertical');if(JSON.stringify(a.point)!==JSON.stringify(a.liftPoint))issues.push('pawn off lift');}}const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);if(new Set(ids).size!==ids.length)issues.push('duplicate ids');return{issues,shapes:[...new Set(shapes)],passages:W.passages,connections:W.connections,previews:DigiBoardMap.previews};});assert.deepEqual(audit.issues,[],id);assert.equal(audit.shapes.length,4);assert.deepEqual(audit.connections,[]);
for(const size of [{width:390,height:844},{width:768,height:900},{width:1280,height:800},{width:1920,height:1080}]){await p.setViewportSize(size);await p.waitForTimeout(100);const r=await p.evaluate(()=>{const i=document.querySelector('#pp-scenery'),m=document.querySelector('#pp-map'),f=PraatpadWorld.fit(m.clientWidth,m.clientHeight);return{image:i.naturalWidth,map:[m.clientWidth,m.clientHeight],inside:PraatpadWorld.anchors.every(([x,y])=>x*f.scale+f.x>=0&&y*f.scale+f.y>=0&&x*f.scale+f.x<=m.clientWidth&&y*f.scale+f.y<=m.clientHeight),scroll:document.documentElement.scrollWidth<=innerWidth};});assert(r.image&&r.inside&&r.scroll,id+JSON.stringify(size));}
await p.setViewportSize({width:1600,height:1000});await p.screenshot({path:path.join(out,id+'.png')});
// Existing four level routes and exercises all adapt on each new map.
const content=await p.evaluate(()=>{const issues=[];for(const level of['A0','A1','A2','B1']){const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));d.settings.learningLevel=level;for(const task of DigiBoardMap.content.tasks){const t=DigiBoardLearning.adapt(task,d.settings,d.session);if(!t.title||!t.instruction||t.level!==level)issues.push(level+task.id);}}return issues});assert.deepEqual(content,[]);
for(const preview of audit.previews){const saved=JSON.stringify((await state()).session);await control(p,'#map-rules-button','click');await p.locator(`[data-preview-new="${preview.id}"]`).click();if(preview.kind){const phase=preview.kind==='tunnel'?'tunnelPhase':'liftPhase',value=preview.kind==='tunnel'?'hidden':'riding';await p.waitForFunction(({phase,value})=>document.querySelector('#praatpad-board').dataset[phase]===value,{phase,value});if(preview.kind==='tunnel')assert.equal(await p.locator('.pp-pawn[data-current=true]').evaluate(e=>+getComputedStyle(e).opacity),0);await p.screenshot({path:path.join(out,id+'-'+preview.id+'.png')});}await done();assert.equal(JSON.stringify((await state()).session),saved);}
for(const passage of audit.passages){await setup(passage.from);await p.evaluate(()=>Math.random=()=>0);const box=await p.locator('#pp-map').boundingBox();await p.keyboard.press('Space');await p.waitForFunction(({kind})=>document.querySelector('#praatpad-board').dataset[kind==='tunnel'?'tunnelPhase':'liftPhase']===(kind==='tunnel'?'hidden':'riding'),passage);assert.deepEqual(await p.locator('#pp-map').boundingBox(),box);await done();assert.equal((await state()).session.players[0].pos,passage.to);await control(p,'#pp-back','click');assert.equal((await state()).session.players[0].pos,passage.from);
// Undo while underground or on lift cancels the animation and retains the original turn.
await p.evaluate(()=>Math.random=()=>0);await p.locator('#pp-roll').click();await p.waitForFunction(({kind})=>document.querySelector('#praatpad-board').dataset[kind==='tunnel'?'tunnelPhase':'liftPhase']===(kind==='tunnel'?'hidden':'riding'),passage);await control(p,'#pp-back','click');await done();assert.equal((await state()).session.players[0].pos,passage.from);
await setup(passage.from,true);await p.evaluate(()=>Math.random=()=>0);await p.locator('#pp-roll').click();await done();assert.equal((await state()).session.players[0].pos,passage.to);}
await setup(count,true);await p.evaluate(()=>Math.random=()=>.99);await p.locator('#pp-roll').click();await done();assert.equal((await state()).session.players[0].pos,count+1);report.push({id,count,passages:audit.passages.map(p=>p.label),status:'passed'});console.log('PASS',id);}
// Every pre-existing map file is byte-identical to the frozen baseline (register is additive).
const names=execFileSync('git',['ls-tree','-r','--name-only','kaartbasis-11-werelden-2026-09-13','Kaarten'],{encoding:'utf8'}).trim().split('\n').filter(n=>n!=='Kaarten/register.js');for(const name of names)assert(fs.readFileSync(name).equals(execFileSync('git',['show','kaartbasis-11-werelden-2026-09-13:'+name],{maxBuffer:30*1024*1024})),name+' changed');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'qa.json'),JSON.stringify({maps:report,preservedFiles:names.length,errors},null,2));console.log('PASS frozen original maps, animation, cancellation, reduced motion, levels, viewports, finish');
}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
