const {control,reveal,conceal}=require('./ui-controls.cjs');
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),server=require('../server.cjs');
const out=path.join(__dirname,'artifacts','ruimtewerking');fs.mkdirSync(out,{recursive:true});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await b.newPage({viewport:{width:1600,height:1000},reducedMotion:'no-preference'}),errors=[],report=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.url());});const base='http://127.0.0.1:'+server.address().port+'/Start-Praatpad.html';
try{await p.goto(base);const maps=await p.evaluate(()=>DigiBoardMaps);
for(const m of maps){await p.goto(base+'?kaart='+m.id);await p.locator('#pp-scenery').evaluate(e=>e.decode());await p.locator('[data-node="1"]').click();await p.locator('#pp-use-task').click();await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem(DigiBoard.storageKey()));d.settings.motion=false;d.settings.sound=false;d.settings.diceStyle='numbers';localStorage.setItem(DigiBoard.storageKey(),JSON.stringify(d));DigiBoard.saveShared(d);});await p.reload();await p.locator('#pp-scenery').evaluate(e=>e.decode());
 const r={id:m.id,viewports:[],tunnel:false};
 for(const [width,height]of [[1600,1000],[1024,768],[390,844]]){await p.setViewportSize({width,height});await p.waitForTimeout(120);r.viewports.push(await p.evaluate(()=>{
  const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,label:e.textContent};},overlap=(a,b)=>a.x<b.x+b.w-1&&a.x+a.w>b.x+1&&a.y<b.y+b.h-1&&a.y+a.h>b.y+1;
  const labels=[...document.querySelectorAll('#pp-map .pp-port,#pp-map .db-world-label')].filter(e=>e.getBoundingClientRect().width>0).map(rect),numbers=[...document.querySelectorAll('#pp-map .pp-number')].filter(e=>getComputedStyle(e).visibility==='visible').map(rect),collisions=[];
  for(let i=0;i<labels.length;i++){for(let j=i+1;j<labels.length;j++)if(overlap(labels[i],labels[j]))collisions.push([labels[i].label,labels[j].label]);for(const n of numbers)if(overlap(labels[i],n))collisions.push([labels[i].label,'vak '+n.label]);}
  const map=rect(document.querySelector('#pp-map'));for(const l of labels)if(l.x<map.x-1||l.y<map.y-1||l.x+l.w>map.x+map.w+1||l.y+l.h>map.y+map.h+1)collisions.push(['outside',l.label]);
  const accessTunnel=PraatpadWorld.connections.find(c=>c.type==='tunnel');
  if(accessTunnel){const f=PraatpadWorld.fit(map.w,map.h),route=DigiBoardSpatial.paths(DigiBoardMap.id,accessTunnel.from,accessTunnel.exits[0]).exit;for(let i=0;i<=30;i++){const q=PraatpadRoutes.along(route,i/30),pawn={x:map.x+(q[0]-21.5)*f.scale+f.x,y:map.y+(q[1]-61)*f.scale+f.y,w:43*f.scale,h:61*f.scale};for(const label of labels)if(overlap(pawn,label))collisions.push(['exit path',label.label]);}}
  const W=PraatpadWorld,fit=W.fit(1672,941),bad=[];for(let i=0;i<W.legs.length;i++){for(const t of[0,.25,.5,.75,1]){const q=W.step(i,i+1,t,1672,941).point;if(q.some(v=>!Number.isFinite(v)))bad.push(i);if(t===0&&Math.hypot(q[0]-W.anchors[i][0],q[1]-W.anchors[i][1])>1)bad.push(i);if(t===1&&Math.hypot(q[0]-W.anchors[i+1][0],q[1]-W.anchors[i+1][1])>1)bad.push(i);}}
  return{width:innerWidth,labels:labels.length,collisions,badLegs:bad};
 }));}
 for(const v of r.viewports){assert.deepEqual(v.collisions,[],m.id+' '+v.width+' labels');assert.deepEqual(v.badLegs,[],m.id+' route');}
 if(process.env.SPATIAL_LAYOUT_ONLY){console.log('PASS label and exit-path clearance',m.id);continue;}
 await p.setViewportSize({width:1600,height:1000});await p.waitForTimeout(150);const tunnel=await p.evaluate(()=>PraatpadWorld.connections?.find(c=>c.type==='tunnel'));
 if(tunnel){const check=await p.evaluate(c=>{const S=DigiBoardSpatial,id=DigiBoardMap.id,g=S.geometry(id),issues=[];let prior=S.pose(id,0,c.from,c.exits[0]);for(let i=1;i<=1000;i++){const q=S.pose(id,i/1000,c.from,c.exits[0]);if(q.opacity>0&&prior.opacity>0&&Math.hypot(q.point[0]-prior.point[0],q.point[1]-prior.point[1])>6)issues.push('jump');prior=q;}for(const pos of[g.entry,g.exit])for(const [i,a]of PraatpadWorld.anchors.entries()){const dx=Math.max(pos[0]-a[0],0,a[0]-(pos[0]+g.size)),dy=Math.max(pos[1]-a[1],0,a[1]-(pos[1]+g.size));if(Math.hypot(dx,dy)<15)issues.push('obstructed tile '+i);}return{issues,start:S.pose(id,0,c.from,c.exits[0]).point,end:S.pose(id,1,c.from,c.exits[0]).point,a:PraatpadWorld.anchors[c.from],b:PraatpadWorld.anchors[c.exits[0]],hidden:S.pose(id,.5,c.from,c.exits[0]).opacity};},tunnel);assert.deepEqual(check.issues,[],m.id+' clearance/continuity');assert.deepEqual(check.start,check.a);assert.ok(Math.hypot(check.end[0]-check.b[0],check.end[1]-check.b[1])<.001);assert.equal(check.hidden,0);
 const saved=await p.evaluate(()=>localStorage.getItem(DigiBoard.storageKey()));
 await p.evaluate(()=>{window.mouthFrames=[];window.recordMouth=true;function frame(){const e=document.querySelector('.pp-pawn[data-current="true"]'),phase=document.querySelector('#praatpad-board').dataset.tunnelPhase;if(phase&&e){const scale=+(e.style.transform.match(/scale\(([^)]+)/)||[])[1];mouthFrames.push({phase,scale,z:+getComputedStyle(e).zIndex,opacity:+getComputedStyle(e).opacity,front:+getComputedStyle(document.querySelector('[id$="-tunnel-front"]')).zIndex});}if(recordMouth)requestAnimationFrame(frame)}frame()});
 await control(p,'#map-rules-button','click');await p.locator(`[data-preview-route="${tunnel.id}"]`).first().click();
 await p.waitForFunction(()=>document.querySelector('#praatpad-board').dataset.tunnelPhase==='enter'&&+document.querySelector('.pp-pawn[data-current="true"]').style.transform.match(/scale\(([^)]+)/)?.[1]<.65,{},{timeout:12000});
 const pivot=await p.locator('.pp-pawn[data-current="true"]').evaluate(el=>{const r=el.getBoundingClientRect(),map=document.querySelector('#pp-map').getBoundingClientRect();return{dx:r.x+r.width*.5-map.x-parseFloat(el.style.left),dy:r.y+r.height*.93-map.y-parseFloat(el.style.top),opacity:+getComputedStyle(el).opacity,z:+getComputedStyle(el).zIndex};});assert.ok(Math.abs(pivot.dx)<1&&Math.abs(pivot.dy)<1,m.id+' foot anchor '+JSON.stringify(pivot));assert.ok(pivot.opacity>0);await p.locator('#pp-map').screenshot({path:path.join(out,m.id+'-in.png')});
 await p.waitForFunction(()=>document.querySelector('#praatpad-board').dataset.tunnelPhase==='hidden');assert.equal(await p.locator('.pp-pawn[data-current="true"]').evaluate(e=>+getComputedStyle(e).opacity),0);
 await p.waitForFunction(()=>document.querySelector('#praatpad-board').dataset.tunnelPhase==='exit');await p.waitForTimeout(500);await p.locator('#pp-map').screenshot({path:path.join(out,m.id+'-uit.png')});await p.waitForFunction(()=>document.querySelector('#praatpad-board').dataset.tunnelPhase==='arrive');
 const exitFrames=await p.evaluate(()=>new Promise(resolve=>{const frames=[];function sample(){const pawn=document.querySelector('.pp-pawn[data-current="true"]'),front=document.querySelector('[id$="-tunnel-front"]');if(document.querySelector('#praatpad-board').dataset.tunnelPhase!=='arrive'){resolve(frames);return;}frames.push({z:+getComputedStyle(pawn).zIndex,front:+getComputedStyle(front).zIndex,opacity:+getComputedStyle(pawn).opacity});requestAnimationFrame(sample)}sample()}));assert.ok(exitFrames.length>0,m.id+' exit sampled');assert.ok(exitFrames.every(f=>f.z>f.front&&f.opacity===1),m.id+' must stay visible in front during the entire walk out');
 await p.locator('#pp-map').screenshot({path:path.join(out,m.id+'-uitgelopen.png')});
 await p.waitForFunction(()=>!document.querySelector('#pp-roll').disabled);assert.equal(await p.evaluate(()=>localStorage.getItem(DigiBoard.storageKey())),saved);const mouthFrames=await p.evaluate(()=>{recordMouth=false;return mouthFrames});
 for(const phase of ['approach','enter','hidden','exit','arrive'])assert.ok(mouthFrames.some(f=>f.phase===phase),m.id+' sampled '+phase);
 for(const f of mouthFrames){if(['approach','arrive'].includes(f.phase)||(['enter','exit'].includes(f.phase)&&f.scale>.66))assert.ok(f.z>f.front,m.id+' premature occlusion '+JSON.stringify(f));if(['enter','exit'].includes(f.phase)&&f.scale<=.66)assert.ok(f.z<f.front,m.id+' missing mouth occlusion');if(f.phase==='hidden')assert.equal(f.opacity,0);}
 r.tunnel=true;r.pivot=pivot;
 }
 await control(p,'#world-route-help','click');await p.locator('#pp-map').screenshot({path:path.join(out,m.id+'-overzicht.png')});report.push(r);console.log('PASS spatial',m.id);}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'controle.json'),JSON.stringify({maps:report,errors},null,2));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
