const assert=require('node:assert/strict');
const runtime=require('../content-runtime.js').createContentRuntime(require('../data/content-vert001-er-b1.js'));
const adapter=require('../lesson-storage-adapter.js').createMemoryAdapter();
const factory=require('../lesson-storage.js');
const progressAdapters={CARDS:{version:runtime.ENGINE_VERSIONS.CARDS,schemaVersion:1,validate:p=>Object.keys(p).every(k=>k==='index')&&Number.isInteger(p.index)}};
const service=factory(runtime,adapter,undefined,progressAdapters);
// Backup is byte-for-byte, once only, and fails closed when storage is full.
const vm=require('node:vm'),migration=require('node:fs').readFileSync(require('node:path').join(__dirname,'../storage-migration.js'),'utf8');
const values=new Map([['taalroute-old','original'],['unrelated','untouched']]);
const storage={get length(){return values.size},key:i=>[...values.keys()][i],getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};
vm.runInNewContext(migration,{window:{},localStorage:storage});const backup=values.get('taalroute-v0124-backup-before-v0125');assert.deepEqual(JSON.parse(backup).values,{'taalroute-old':'original'});values.set('taalroute-old','new');vm.runInNewContext(migration,{window:{},localStorage:storage});assert.equal(values.get('taalroute-v0124-backup-before-v0125'),backup);
const failed={window:{},localStorage:{...storage,getItem:()=>null,setItem:()=>{throw new Error('Quota')}}};vm.runInNewContext(migration,failed);assert.ok(failed.window.DigiStorageBackupError);assert.equal(values.get('unrelated'),'untouched');
(async()=>{
 const spec=runtime.specFromFilters({topics:['ER'],levels:['B1']}),prefs={target_duration_seconds:300,organization_mode:'class',preferred_game_engine:'CARDS',preferred_game_variant:'content-pb001'};
 const saved=await service.saveSelection({name:'ER B1',selection_spec:spec,execution_preferences:prefs});
 assert.equal(JSON.stringify(saved).includes('selected_item_ids'),false);
 const s=await service.createSessionFromSelection(saved.saved_selection_id,{seed:3});
 assert.deepEqual(await service.get('saved_selection',saved.saved_selection_id),saved,'Start does not edit lesson');
 const p={engine_id:'CARDS',engine_version:runtime.ENGINE_VERSIONS.CARDS,progress_schema_version:1,state_payload:{index:3},last_checkpoint_at:new Date().toISOString()};
 const recent=await service.storeRecentSession(s,p);
 const resumed=await service.resumeRecentSession(recent.recent_session_id);assert.equal(resumed.session.session_id,s.session_id);assert.equal(resumed.progress.state_payload.index,3);
 const replay=await service.replayRecentSessionExact(recent.recent_session_id);assert.notEqual(replay.session_id,s.session_id);assert.deepEqual(replay.selected_content_refs,s.selected_content_refs);assert.equal(replay.runtime_progress,undefined);
 const reroll=await service.rerollRecentSession(recent.recent_session_id);assert.notEqual(reroll.session_id,s.session_id);assert.notEqual(reroll.selection_seed,s.selection_seed);assert.deepEqual(reroll.normalized_selection_spec,s.normalized_selection_spec);
 await assert.rejects(()=>service.storeRecentSession({...s,selection_seed:100},p,{expected_revision:1}),e=>e.code==='BLOCKED_SCHEMA_VERSION');
 await assert.rejects(()=>service.storeRecentSession(s,{...p,state_payload:{index:3,student_id:'p1'}}),e=>e.code==='BLOCKED_PRIVACY_PAYLOAD');
 await assert.rejects(()=>service.storeRecentSession(s,{...p,state_payload:{index:3,unexpected:'personal answer'}}),e=>e.code==='BLOCKED_PRIVACY_PAYLOAD');
 const updated=await service.updateSavedSelection(saved.saved_selection_id,{name:'ER aangepast'},1);assert.equal(updated.record_revision,2);
 await assert.rejects(()=>service.updateSavedSelection(saved.saved_selection_id,{name:'Overschrijven'},1),e=>e.code==='CONFLICT_REVISION');
 assert.equal((await service.get('saved_selection',saved.saved_selection_id)).name,'ER aangepast');
 const other=factory(runtime,adapter,{owner_scope:'user',owner_ref:'other'},progressAdapters);
 await assert.rejects(()=>other.get('saved_selection',saved.saved_selection_id),e=>e.code==='BLOCKED_PERMISSION');
 const system={...saved,saved_selection_id:'system',owner_scope:'system',owner_ref:'taalroute',visibility:'system',edit_policy:'immutable'};await adapter.put('saved_selection','system',system,null);
 await assert.rejects(()=>service.updateSavedSelection('system',{name:'Mine'},1),e=>e.code==='BLOCKED_PERMISSION');
 const f=await service.addFavorite('saved_selection',saved.saved_selection_id),f2=await service.addFavorite('saved_selection',saved.saved_selection_id);assert.deepEqual(f,f2);
 await service.removeFavorite(f.favorite_ref_id,f.record_revision);assert.ok(await service.get('saved_selection',saved.saved_selection_id));
 const mix=await service.createMixProfile({name:'Mix',...spec,execution_defaults:prefs});assert.equal((await service.resolveMixProfile(mix.mix_profile_id)).session.content_bank_ids.length,1);
 const broken=structuredClone(recent);broken.selected_content_refs[0].source_version='old';broken.session_config_snapshot.selected_content_refs=broken.selected_content_refs;broken.session_config_fingerprint=runtime.fingerprint(broken.session_config_snapshot);broken.recent_session_id='broken';await adapter.put('recent_session','broken',broken,null);
 await assert.rejects(()=>service.resumeRecentSession('broken'),e=>e.code==='BLOCKED_VERSION_UNAVAILABLE');
 const revoked=structuredClone(recent);revoked.recent_session_id='revoked';revoked.revocation_status='HARD_REVOKED';await adapter.put('recent_session','revoked',revoked,null);
 await assert.rejects(()=>service.replayRecentSessionExact('revoked'),e=>e.code==='BLOCKED_RIGHTS');
 await service.archiveSavedSelection(saved.saved_selection_id,2);assert.equal((await service.resolveSavedSelection(saved.saved_selection_id)).status,'BLOCKED_MISSING_REFERENCE');
 console.log('PASS v1.25: immutable sessions, exact replay, reroll, privacy, permissions, optimistic concurrency, favorites, mixes, missing versions and revocation.');
})().catch(e=>{console.error(e);process.exitCode=1});
