const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),served=process.env.BUILD_SMOKE?path.join(root,'dist'):root;
const server=http.createServer((req,res)=>{const file=path.resolve(served,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!file.startsWith(served+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.mp3':'audio/mpeg'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res)});
let browser;
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const page=await browser.newPage({viewport:{width:1920,height:1080},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>{errors.push(e.stack);console.error(e.stack)});
 await page.addInitScript(()=>{if(!localStorage.getItem('v125-test-seeded')){localStorage.setItem('taalroute-digibord-v020',JSON.stringify({level:'A2',turn:{mode:'class',active:0},boardStates:{rotterdam:{classPos:9,round:2}},storyLocks:{0:true}}));localStorage.setItem('taalroute-poc0141-settings',JSON.stringify({participants:[{id:'p1',name:'Privénaam',present:true}],pawnMode:'class',groupCount:2}));localStorage.setItem('v125-test-seeded','1')}});
 await page.goto(`http://127.0.0.1:${server.address().port}/index.html`);await page.waitForFunction(()=>window.ContentUI&&window.LessonUI);
 const backup=await page.evaluate(()=>JSON.parse(localStorage.getItem('taalroute-v0124-backup-before-v0125')));assert.equal(JSON.parse(backup.values['taalroute-digibord-v020']).boardStates.rotterdam.classPos,9);
 await page.locator('[data-main="practice"]').click();await page.locator('[name=family]').selectOption('words');
 assert.equal(await page.locator('[name=level]').inputValue(),'A0→A1');assert.equal(await page.evaluate(()=>ContentUI.state().difficulty),'basis');
 await page.locator('.practice-engine:has(input[value="CARDS"])').click();await page.locator('[name=duration][value="300"]').check({force:true});
 await page.locator('#practiceSave').click();await page.locator('#lessonName').fill('Mijn eerste WZ-les');await page.locator('#lessonSaveForm .primary').click();await page.waitForFunction(()=>!document.querySelector('#gameDialog').open);
 const saved=await page.evaluate(async()=> (await LessonUI.service.list('saved_selection'))[0]);assert.equal(saved.name,'Mijn eerste WZ-les');assert.equal(saved.selected_item_ids,undefined);
 await page.locator('#practiceStart').click();await page.waitForSelector('.content-vert001-cards');await page.locator('#primaryGame').click();await page.locator('#undoAction').click();assert.equal(await page.evaluate(()=>APP.cardIndex),0);await page.locator('#primaryGame').click();await page.evaluate(()=>LessonUI.flush());
 const before=await page.evaluate(()=>({session:ContentRuntime.activeSession(),index:APP.cardIndex}));assert.equal(before.index,1);
 const stored=await page.evaluate(async()=> (await LessonUI.service.list('recent_session'))[0]);assert.equal(stored.runtime_progress.state_payload.index,1);assert.equal(JSON.stringify(stored).includes('Privénaam'),false);
 await page.reload();await page.locator('[data-main="lessons"]').click();await page.waitForSelector('[data-lesson-action="resume"]');await page.locator('[data-lesson-action="resume"]').click();await page.waitForSelector('.content-vert001-cards');
 assert.equal(await page.evaluate(()=>APP.cardIndex),1);assert.equal(await page.evaluate(()=>ContentRuntime.activeSession().session_id),before.session.session_id);
 await page.locator('[data-main="lessons"]').click();await page.waitForSelector('[data-lesson-action="replay"]');await page.locator('[data-lesson-action="replay"]').first().click();await page.waitForSelector('.content-vert001-cards');assert.equal(await page.evaluate(()=>APP.cardIndex),0);assert.notEqual(await page.evaluate(()=>ContentRuntime.activeSession().session_id),before.session.session_id);
 await page.evaluate(()=>ContentUI.open());await page.evaluate(()=>ContentUI.setState({family:'grammar',topic:'ER',level:'B1'}));await page.evaluate(()=>ContentUI.setState({focus:'all',difficulty:'all',duration:300,engine:'MATCH',variant:'koppelen'}));await page.locator('[data-practice-focus=correct]').click();
 await page.locator('#practiceStart').click();await page.waitForSelector('.na-pairs .na-pair-text');const pairs=await page.locator('.na-pairs [data-content-item-id]').count();assert.ok(pairs>=2);
 await page.locator('#na-select-0').click();await page.locator('#na-match-0').click();await page.evaluate(()=>LessonUI.flush());const pairProgress=await page.evaluate(()=>DigiActivities.exportProgress());assert.deepEqual(pairProgress.done,[0]);
 await page.reload();await page.locator('#resumeBtn').click();await page.waitForSelector('.na-pairs .na-pair-text');assert.deepEqual(await page.evaluate(()=>DigiActivities.exportProgress().done),[0]);
 assert.equal(await page.evaluate(()=>{const p=DigiActivities.exportProgress();p.order=[999];try{DigiActivities.validateProgress(p);return false}catch{return true}}),true);
 const concurrent=await page.evaluate(async()=>{const item=(await LessonUI.service.list('saved_selection'))[0],other=LessonStorage(ContentRuntime,LessonStorageAdapters.createIndexedDBAdapter(indexedDB));return Promise.allSettled([LessonUI.service.updateSavedSelection(item.saved_selection_id,{name:'Wijziging A'},item.record_revision),other.updateSavedSelection(item.saved_selection_id,{name:'Wijziging B'},item.record_revision)]).then(r=>r.map(x=>x.status==='fulfilled'?'ok':x.reason.code).sort())});assert.deepEqual(concurrent,['CONFLICT_REVISION','ok']);

 for(let i=1;i<pairs;i++){await page.locator('#na-select-'+i).click();await page.locator('#na-match-'+i).click()}
 assert.equal(await page.locator('#primaryGame').isEnabled(),true);await page.locator('#primaryGame').click();assert.equal(await page.evaluate(()=>DigiActivities.exportProgress().round),1);
 await page.evaluate(async()=>{await LessonUI.flush();const session=ContentRuntime.activeSession();ContentUI.launch(await LessonUI.service.replayRecentSessionExact('recent-'+session.session_id))});assert.equal(await page.evaluate(()=>DigiActivities.exportProgress().round),0);
 await page.evaluate(()=>ContentUI.open({engine:'MEMORY'}));await page.evaluate(()=>ContentUI.setState({family:'grammar',topic:'ER',level:'B1',focus:'correct',difficulty:'all',duration:300,engine:'MEMORY',variant:'memory'}));await page.locator('#practiceStart').click();await page.waitForSelector('.na-memory');
 const order=await page.evaluate(()=>DigiActivities.exportProgress().order),first=order.findIndex(i=>Math.floor(i/2)===0),second=order.findIndex((i,n)=>Math.floor(i/2)===0&&n!==first);await page.locator('#na-flip-'+first).click();await page.locator('#na-flip-'+second).click();assert.deepEqual(await page.evaluate(()=>DigiActivities.exportProgress().done),[0]);

 for(let pair=1;pair<order.length/2;pair++){for(const i of order.map((token,i)=>Math.floor(token/2)===pair?i:-1).filter(i=>i>=0))await page.locator('#na-flip-'+i).click()}
 await page.locator('#primaryGame').click();assert.equal(await page.evaluate(()=>DigiActivities.exportProgress().round),1);
 await page.evaluate(()=>ContentUI.open());await page.evaluate(()=>ContentUI.setState({topic:'MODAAL',level:'B1'}));await page.evaluate(()=>ContentUI.setState({focus:'sort',duration:300,engine:'SORT',variant:'sorteren'}));await page.locator('#practiceStart').click();await page.waitForSelector('.na-sort-result');

 for(let n=0;n<6;n++){const answer=await page.evaluate(()=>{const el=document.querySelector('.na-word[data-content-item-id]');if(!el)return null;const item=ContentRuntime.itemById(el.dataset.contentItemId);return [...document.querySelectorAll('.na-options [data-na=sort]')].findIndex(b=>b.textContent===item.correct_answer)});if(answer===null)break;await page.locator('#na-sort-'+answer).click()}
 await page.locator('#primaryGame').click();assert.equal(await page.evaluate(()=>DigiActivities.exportProgress().round),1);
 await page.evaluate(()=>ContentUI.open({family:'words',engine:'WHEEL'}));await page.evaluate(()=>ContentUI.setState({duration:300}));await page.locator('#practiceStart').click();await page.locator('#primaryGame').click();await page.waitForFunction(()=>document.querySelector('.na-wheel-result [data-content-item-id]'));assert.equal(await page.locator('#levelSelect').inputValue(),'A0→A1');
 await page.evaluate(()=>ContentUI.open({family:'riddles',engine:'RIDDLE'}));await page.evaluate(()=>ContentUI.setState({duration:300}));await page.locator('#practiceStart').click();await page.waitForSelector('.na-clues[data-content-item-id]');await page.locator('#na-guess').fill('Mijn eigen antwoord');await page.locator('#na-guess-form button').click();await page.waitForFunction(()=>/Vergelijk|Bespreek/i.test(document.querySelector('#na-feedback').textContent));
 await page.locator('[data-main="lessons"]').click();await page.waitForSelector('#lessonMix');await page.locator('#lessonMix').click();await page.locator('[name=mixTopic]').first().check();await page.locator('[name=mixTopic]').nth(4).check();await page.locator('#lessonMixForm .primary').click();await page.waitForFunction(()=>!document.querySelector('#gameDialog').open);assert.equal(await page.evaluate(()=>ContentUI.selectionSpec().scope_clauses.length),2);

 const probe=await page.evaluate(()=>{const source=ContentRuntime.source,items=source.items.filter(i=>i.topic==='ER'&&i.cefr_level==='B1'&&i.exercise_type==='fout_verbeteren').map(i=>({...structuredClone(i),content_item_id:'PROBE-'+i.content_item_id,content_bank_id:'CB-PROBE',topic:'PROBE'}));ContentUI.registerBank({...source,bank_id:'CB-PROBE',source_version:'test-only',items,item_count:items.length},{familyId:'probe',label:'Testbank'});ContentUI.open({family:'probe',engine:'CARDS'});ContentUI.setState({duration:300,organization:'groups'});return ContentRuntime.createSession(ContentUI.sessionOptions(37))});
 await page.evaluate(()=>goScreen('workforms'));await page.locator('#screen-workforms [data-practice-engine="MATCH"]').click();const probeOther=await page.evaluate(()=>ContentRuntime.createSession(ContentUI.sessionOptions(37)));assert.deepEqual(probeOther.selected_item_ids,probe.selected_item_ids);
 assert.ok(['BOARD','CARDS','DICE','WHEEL','QUIZ','MATCH','MEMORY'].every(e=>probe.game_engines.includes(e)));assert.equal(probe.game_engines.includes('SORT'),false);
 await page.evaluate(()=>{ContentUI.open({family:'grammar',engine:'BOARD',variant:'rotterdam'});ContentUI.setState({topic:'ER',level:'B1',duration:300,organization:'class'});ContentUI.start(17);CONTENT_VERT001.stop()});assert.equal(await page.evaluate(()=>APP.boardStates.rotterdam.classPos),9);assert.equal(await page.evaluate(()=>APP.level),'A2');
 await page.evaluate(()=>ContentUI.open({family:'words',engine:'CARDS'}));
 for(const [width,height] of [[1920,1080],[1024,768],[390,844]]){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)}
 await page.setViewportSize({width:1920,height:1080});if(process.env.V125_SCREENSHOTS){await page.locator('#toast').evaluate(el=>el.classList.remove('show'));await page.screenshot({path:process.env.V125_SCREENSHOTS+'/voorbereiding.png'});await page.locator('[data-main="lessons"]').click();await page.waitForSelector('[data-lesson-action="mix-open"]');await page.locator('#toast').evaluate(el=>el.classList.remove('show'));await page.screenshot({path:process.env.V125_SCREENSHOTS+'/mijn-lessen.png'})}
 assert.deepEqual(errors,[]);console.log('PASS v1.25 browser: old storage backup, WZ preparation/save, actual reload/resume/replay, private-data exclusion, matching/memory/sort/riddle, mix editor and digibord/mobile widths.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.close()});
