// One editable source; the browser file is a checked, generated view for offline use.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const bank=JSON.parse(fs.readFileSync(path.join(root,'Lessen/woorden-zinnen.json'),'utf8'));
const types=['Bouw','Kies','Herstel','Verander','Spreek','Transfer','Raad'];
assert.equal(bank.schemaVersion,1);assert.equal(new Set(bank.items.map(i=>i.id)).size,bank.items.length);
const wz=bank.items.filter(i=>i.source==='WZ_BATCH_001');assert.equal(wz.length,680);
for(const item of bank.items){
 for(const field of ['id','goalId','level','context','type','answerType','answerModel','review'])assert.ok(item[field],`${item.id}: ${field}`);
 assert.ok(types.includes(item.type));assert.ok(['OPEN','GESLOTEN'].includes(item.answerType));
 assert.ok(Array.isArray(item.acceptedAnswers));
 if(item.answerType==='OPEN'){assert.ok(['Spreek','Transfer','Raad'].includes(item.type));assert.equal(item.acceptedAnswers.length,0)}
 else {assert.ok(!['Spreek','Transfer','Raad'].includes(item.type));assert.ok(item.acceptedAnswers.includes(item.answerModel))}
 if(item.source==='PRAATPAD_WORDS'){
  assert.ok(['A1','A2','B1','B2'].includes(item.level));assert.equal(item.band,null);
  assert.ok(item.legacyRef.sourceCommit);assert.ok(Number.isInteger(item.legacyRef.index));
  if(item.type==='Bouw'){assert.equal(item.tokens.join(' '),item.answerModel);assert.equal(item.tokenRoles.length,item.tokens.length)}
  if(item.type==='Raad'){assert.equal(item.clues.length,3);assert.equal(new Set(item.clues).size,3)}
 }
 if(item.source!=='WZ_BATCH_001')continue;
 assert.ok([1,2,3].includes(item.band));assert.ok(item.instruction);assert.ok(item.feedback);
 if(item.type==='Kies'){
  assert.ok(item.options.length>=2);assert.equal(new Set(item.options.map(o=>o.text.toLocaleLowerCase('nl'))).size,item.options.length,item.id);
  assert.equal(item.options.filter(o=>o.id===item.correctOptionId).length,1,item.id);
  const correct=item.options.find(o=>o.id===item.correctOptionId).text;
  assert.equal(item.stimulus.includes('...')?item.stimulus.replace('...',correct):correct,item.answerModel,item.id+' model');
 }
 if(item.type==='Bouw'){
  const norm=s=>s.toLocaleLowerCase('nl').replace(/[.?!]/g,'').trim();
  assert.equal(norm(item.tokens.join(' ')),norm(item.answerModel),item.id);
 }
 if(item.type==='Verander')assert.notEqual(item.stimulus,item.answerModel,item.id);
}
for(let n=1;n<=8;n++)assert.equal(wz.filter(i=>i.goalId===`WZ_00${n}`).length,80);
assert.equal(wz.filter(i=>i.goalId==='WZ_006_007').length,40);
assert.equal(wz.filter(i=>i.answerType==='OPEN').length,202);
const target=path.join(root,'words-content.js');
const output='// GENERATED by scripts/words-content.cjs --write. Edit Lessen/woorden-zinnen.json.\nconst WORD_CONTENT = '+JSON.stringify(bank)+';\n';
if(process.argv.includes('--write'))fs.writeFileSync(target,output);
else assert.equal(fs.readFileSync(target,'utf8'),output,'Browserbank verschilt van de centrale bron; voer npm run sync:words uit.');
assert.equal(bank.items.filter(i=>i.source==='PRAATPAD_WORDS'&&i.type==='Bouw').length,12);
assert.equal(bank.items.filter(i=>i.source==='PRAATPAD_WORDS'&&i.type==='Raad').length,16);
assert.equal(bank.items.length,738);
console.log('PASS: centrale bron, 680 WZ + 30 behouden + 28 historische kaarten; schema en runtimepariteit.');
